### ISSUE TITLE
Handling BC *.LMD files

### ISSUE THREAD

**Issue by davidpng** [whitews/FlowKit#104]
I am unable to pull the FCS3.0 version of the dataset embedded in BC LMD files - sometimes called 'dataset 2'.

I would like to be able to select the second dataset which stores the state in an uncompensated format with full 14 bit resolution instead of the compensated, log transformed data with 10 bit resolution

**Describe alternatives you've considered**
I've modified loadFCS to handle these files but 

**Additional context**
BC LMD files have a non standard format where the first part is FCS2.0,  followed by some gating information from CXP, followed by an FCS3.0 header and data.

**Comment by whitews** [comment]
Hi David,

Are these Beckman Coulter LMD files? Can you provide an example file?

Loading files would be handled by my FlowIO library, so if you have code to handle these LMD files that would be the place to submit a PR.

Thanks,
Scott
