### ISSUE TITLE
ValueError: Parent gate ** does not exist in the gating strategy

### ISSUE THREAD

**Issue by srideviks** [whitews/FlowKit#121]
**Describe the bug**
Hello team. When I try to import a workspace (wsp) file into a FlowKit session(containing corresponding fcs file) using "import_flowjo_workspace()" function, I get "ValueError: Parent gate CD3- does not exist in the gating strategy". 
The procedure used to obtain the wsp file with gate information is as follows:
1) Assay (say TBNK) specific template is first opened in FlowJo software.
2) A fcs file is drag and dropped to the TBNK group in FlowJo software.
3) Default gates present in the template will be dragged by a flow SME to correctly gate each population.

While gating the above file, the flow SME retained the template gates for CD3- and T cells (subpopulations of Lymphocytes) as they correctly classified the CD3- and T cell populations. Thus, the workspace file contains "owning_group"="TBNK" for both CD3- and T cells under <SampleNode> section. 
However, in FlowKit the custom gates are determined using the condition #if sample_gate['owning_group'] == ''# --> line 447 in code: "_utils/wsp.utils.py". Thus FlowKit is not considering CD3- and T cells in custom gates and hence when it encounters the population B cells and NK cells (both are sub-populations of CD3-) in custom gates, it searches for the parent gate (CD3- and it's not present). Thus,  I get the valueError: Parent gate ** does not exist in the gating strategy. Kindly help me fix this issue.

**Code To Reproduce**
Code to reproduce the behavior:
```
import flowkit as fk
sample_id = '1_TBNK.fcs'
sample_grp = 'TBNK'
base_dir = "../../Data/Orig_wsp_fcs/"
sample_path = os.path.join(base_dir, sample_id)
wsp_path = os.path.join(base_dir, "1_TBNK.wsp")

fks_fj = fk.Session(sample_path)
fks_fj.import_flowjo_workspace(wsp_path) # This line of code results in the ValueError mentioned above
```

**Expected behavior**
Final cell population-specific gates should be properly loaded, whether or not they be customized or retained template gate co-ordinates.

**Screenshots**
![image](https://user-images.githubusercontent.com/19530531/181308898-658186f2-f94a-458d-8d4d-0beb4d773760.png)

**Desktop (please complete the following information):**
 - OS: Windows version 10.0.19044.1766
 - Python version 3.9
 - FlowKit version 0.9.1

**Additional context**
--NA--

**Comment by srideviks** [comment]
Hello team, I referred to the workaround mentioned in the issue #93. 
The workaround helped, yet ended up issue #120. Looking forward to the solution for issue #120 

Regards,
Sridevi

**Comment by whitews** [comment]
Thanks, will close this one.
