### ISSUE TITLE
Import Issue Flowkit 0.9.2 

### ISSUE THREAD

**Issue by Bastien-Dussap** [whitews/FlowKit#122]
**Describe the bug**
Can't import Flowkit 0.9.2. This is the same error as in https://github.com/whitews/FlowKit/issues/106, unfortunately the issue wasn't solved.
If I create a new virtual env and I install flowkit 0.9.2 (and its dependancy) using : 
```
pip install flowkit
``` 
there is no problem. When I do 
```
pip list
```
I obtain the following packages: 
Package           Version
----------------- --------
anytree           2.8.0
bokeh             2.4.3
cycler            0.11.0
FlowIO            1.0.1
FlowKit           0.9.2
FlowUtils         1.0.0
fonttools         4.37.1
Jinja2            3.1.2
kiwisolver        1.4.4
lxml              4.9.1
MarkupSafe        2.1.1
matplotlib        3.5.3
networkx          2.8.6
numpy             1.23.2
packaging         21.3
pandas            1.4.3
patsy             0.5.2
Pillow            9.2.0
pip               22.0.2
psutil            5.9.1
pyparsing         3.0.9
python-dateutil   2.8.2
pytz              2022.2.1
PyYAML            6.0
scipy             1.9.1
seaborn           0.11.2
setuptools        59.6.0
six               1.16.0
statsmodels       0.13.2
tornado           6.2
typing_extensions 4.3.0
-----------------------------------

Everything seems to work fine until I import the package, I obtain the following error message: 

>>> import flowkit
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "/home/dussap/Documents/Thèse/.env_these/lib/python3.9/site-packages/flowkit/__init__.py", line 10, in <module>
    from ._models.session import Session
  File "/home/dussap/Documents/Thèse/.env_these/lib/python3.9/site-packages/flowkit/_models/session.py", line 18, in <module>
    from .._utils import plot_utils, xml_utils, wsp_utils, sample_utils
  File "/home/dussap/Documents/Thèse/.env_these/lib/python3.9/site-packages/flowkit/_utils/xml_utils.py", line 7, in <module>
    from .._resources import gml_schema
  File "/home/dussap/Documents/Thèse/.env_these/lib/python3.9/site-packages/flowkit/_resources/__init__.py", line 19, in <module>
    gml_schema = etree.XMLSchema(
  File "src/lxml/xmlschema.pxi", line 89, in lxml.etree.XMLSchema.__init__
lxml.etree.XMLSchemaParseError: Element '{http://www.w3.org/2001/XMLSchema}group', attribute 'ref': The QName value '{http://www.isac-net.org/std/Gating-ML/v2.0/transformations}Transformation_Group' does not resolve to a(n) model group definition., line 51

**Desktop (please complete the following information):**
 - OS: ubuntu 22.04
 - Python version 3.10.4 

**Note** : 
I have the same issue with my "main" python venv (python 3.9.13 and flowkit 0.8.2).
Both FlowIO and FlowUtils import without errors.

Thanks for the help.

# Update

Ok so I fix the issue even though I have no idea how.
I delete the cache of pip 
```
pip cache purge
```
It fixed the issue. I don't know what was the problem. You can close this issue.

**Comment by Bastien-Dussap** [comment]
I change my path "Thèse -> These" and I empty the cache of pip and the problem was fixed. I though the issue was with the cache but you're probably right, special character was the issue.
Thanks.

**Comment by whitews** [comment]
Hi Bastien,

I was able to solve the issue in the latest commits in the master branch. If I could ask a favor of you...can you clone the master branch and install in a virtualenv with a directory path containing an accented character? I'd like to verify the fix is working for you before releasing 0.9.3.

Many thanks!
Scott

**Comment by Bastien-Dussap** [comment]
Hi,
I try and it works.

Thanks.
