### ISSUE TITLE
`subsample_events()` does not return anything

### ISSUE THREAD

**Issue by hbaniecki** [whitews/FlowKit#129]
Documentation says that `subsample_events()` returns a `numpy` array. It does not return any object, nor it changes the dataset attribute in place.

See the appropriate code:
https://github.com/whitews/FlowKit/blob/e049a56973bed9b4aa8455d743f4d2e9f4440399/flowkit/_models/sample.py#L370-L417

**Comment by whitews** [comment]
Hi Hubert,

Thanks for catching this outdated docstring. The `subsample_events` method no longer returns anything. All variations of retrieving events is done through the `get_events` method. I will correct this for the next version. 

Regards,
Scott
