### ISSUE TITLE
Create new fcs with metadata

### ISSUE THREAD

**Issue by DomenicoDB** [whitews/FlowKit#130]
Hi,

I would create a new fcs file from a pandas dataframe.
Is there a way, using flowkit, to write metadata in this new fcs file?

Thanks in advance

**Comment by whitews** [comment]
Hi,

Yes, the Sample class has a `metadata` attribute, which is a dictionary of key/value string pairs. The metadata can be included in the `export` method by setting the keyword argument `include_metadata=True`.
