### ISSUE TITLE
Erroneous multiple quadrant parents exception

### ISSUE THREAD

**Issue by krcurtis** [whitews/FlowKit#132]
**Describe the bug**
Somehow when I invoke the get_gate_membership() on my GatingResults object I get an exception about multiple quadrant parents. When I run the debugger in the jupyter console, and look at quad_parent_values it is an empty set, and so should not trigger the multiple quadrant parents exception (as far as I can tell)

**Code To Reproduce**
Code to reproduce the behavior:
```
import flowkit as fk
...
g_strategy = fk.parse_gating_xml(GATINGML)
gs_results = g_strategy.gate_sample(sample, verbose=True)
gs_results.get_gate_membership(gate_name="P1")
```

**Expected behavior**
I expected to get a boolean vector. I can see the results I want hidden away in the _raw_results field:

```
In [15]: gs_results._raw_results
Out[15]: 
{('P1', 'root'): {'sample': None,
  'events': array([ True,  True,  True,  True,  True,  True,  True,  True,  True,
          True,  True,  True,  True,  True,  True,  True,  True,  True,
          True,  True,  True,  True,  True,  True,  True,  True,  True,
          True,  True,  True,  True,  True,  True,  True,  True,  True,
          True]),
```

**Screenshots**

**Desktop (please complete the following information):**
 - OS: Linux/ ubuntu 18.04.6 LTS (Bionic Beaver)
 - Python version: 3.8.13
 - FlowKit version: 0.9.3

**Additional context**
```
In [20]: gs_results.get_gate_membership(gate_name="P1")
---------------------------------------------------------------------------
ValueError                                Traceback (most recent call last)
Input In [20], in <cell line: 1>()
----> 1 gs_results.get_gate_membership(gate_name="P1")

File ~/miniconda3-2020/envs/bcellflow/lib/python3.8/site-packages/flowkit/_models/gating_results.py:119, in GatingResults.get_gate_membership(self, gate_name, gate_path)
    117     return self._raw_results[quad_parent, gate_path][gate_name]['events']
    118 else:
--> 119     raise ValueError("Report as bug: The gate %s appears to have multiple quadrant parents." % gate_name)

ValueError: Report as bug: The gate P1 appears to have multiple quadrant parents.

In [21]: %debug
> /home/krcurtis/miniconda3-2020/envs/bcellflow/lib/python3.8/site-packages/flowkit/_models/gating_results.py(119)get_gate_membership()
    117             return self._raw_results[quad_parent, gate_path][gate_name]['events']
    118         else:
--> 119             raise ValueError("Report as bug: The gate %s appears to have multiple quadrant parents." % gate_name)
    120
    121     def get_gate_count(self, gate_name, gate_path=None):

ipdb> p quad_parent_values
set()

```

**Comment by whitews** [comment]
Thanks for submitting this bug report. As you can see from the error message I suspected this may be possible...the GatingML quadrant gates were tricky to implement. Can you provide the GatingML document that triggered the error?

**Comment by krcurtis** [comment]
Yes, here's the GatingML. I had to rename it to a .txt file before GitHub would let me upload it (they don't like *.gatingml or *.xml apparently).  

I create this file programmatically from a DIVA XML file, and FlowKit does load it, so it passed the schema check. But I can change it if there is something wrong with it.

[test-gatingml.txt](https://github.com/whitews/FlowKit/files/10240558/test-gatingml.txt)

**Comment by whitews** [comment]
@krcurtis 

I started looking into the document but it's difficult to tell what is wrong without an FCS file to run it and debug. Can you share an FCS file that is compatible with the gating strategy parameters?

Thanks,
Scott

**Comment by krcurtis** [comment]
I can't share the original file. I'll generate a random one, re-check, and upload it.

**Comment by krcurtis** [comment]
Hi, I found out that the exception has something to do with me creating a flowkit.Sample object from a dataframe.  I've attached a a FCS file (with randomly generated measurements) that I load, convert to dataframe, convert back to sample, try to get the gate membership event status, and get the same ValueError exception.

```python
import pandas as pd
import flowkit as fk

FCS = "test_fcs.fcs"
GATINGML = "test-gatingml.txt"

g_strategy = fk.parse_gating_xml(GATINGML)
sample = fk.Sample(FCS)

df = sample.as_dataframe(source='raw')
df.columns = df.columns.droplevel(1)

sample2 = fk.Sample(df.values, channel_labels = list(df.columns) )

gs_results = g_strategy.gate_sample(sample2, verbose=True)
print(gs_results.get_gate_membership(gate_name="P1"))
```

[test_fcs.zip](https://github.com/whitews/FlowKit/files/10440071/test_fcs.zip)

**Comment by whitews** [comment]
Ok, I see what the problem is. The Sample instance created from a DataFrame has a `None` value for the `original_filename` attribute. This value is used for the "sample_id" reference / argument value you see as an option in many FlowKit methods. That value gets set by the FCS metadata keyword for real FCS files.

A temporary workaround is to simply set the attribute after creating the Sample, something like:

`sample2.original_filename = 'something'`

I have a note about changing this behaviour, as it seemed a bit janky and potentially confusing. It is not clear to the user that this `original_filename` is used as the Sample ID. I think adding a dedicated `id` attribute to the Sample class would be clearer. 

Additionally, I'll add an `id` keyword argument to the Sample constructor and default it to `None`. For regular FCS files, when None it will use the `original_filename`. For DataFrames / NumPy arrays, it will throw an Exception saying a text value is required to identify the Sample. Does this sound like a reasonable solution?

Thanks again for reporting the issue and creating the test file.

**Comment by krcurtis** [comment]
An id field makes sense, sounds good to me.

**Comment by krcurtis** [comment]
Oops, maybe I shouldn't have clicked closed, in case you want to tie commits to the issue

**Comment by whitews** [comment]
The Sample constructor now requires a `sample_id` argument value when given a NumPy array or pandas DataFrame. This value is accessible via the `id` attribute of the resulting Sample instance.
