### ISSUE TITLE
RectangleGate.__init__() missing 1 required positional argument: 'parent_gate_name'

### ISSUE THREAD

**Issue by r0oland** [whitews/FlowKit#141]
When running trough your example noitebook "flowkit-tutorial-part04-gates-module.ipynb" I get the following error for the RectangleGate Class:
`RectangleGate.__init__() missing 1 required positional argument: 'parent_gate_name'`. 

![image](https://user-images.githubusercontent.com/558053/215317163-b2450f58-4e87-453b-8ed0-fdef89e2dc5d.png)

**Comment by r0oland** [comment]
same for PolygonGate:
![image](https://user-images.githubusercontent.com/558053/215317218-89a79d3d-33a3-4cd1-b6a8-c092ce834e52.png)

**Comment by r0oland** [comment]
Seems to be a general bug with the gating class.

**Comment by whitews** [comment]
Hi Johannes,

Sorry about that, the develop branch was merged into master prematurely. The changes you see in the tutorial notebook series are correct for the current development code, but are not compatible with the last 0.9.3 release. You can find the 0.9.3 notebooks on that release here:

https://github.com/whitews/FlowKit/tree/0.9.3

What you are seeing is the API for the upcoming 1.0 release, which has a lot of changes, including simpler creation of gates. They no longer require specifying a parent gate, as that relationship is now defined when assigning the gate to the tree.

Again, I apologize for the mess, this release is turning out to be larger than I anticipated.

-Scott

**Comment by whitews** [comment]
Johannes,

I've just pushed updates to the tutorial notebooks for the current code in master and what will hopefully be the final API for the upcoming 1.0 release. The advanced notebooks will be updated next week. I'm closing this now, but let me know if you find any issues with these tutorial notebooks. I do appreciate your time and effort reporting this and creating the PRs.

Sincerely,
Scott
