### ISSUE TITLE
Error when reading compensation csv files

### ISSUE THREAD

**Issue by ocohen7** [whitews/FlowKit#144]
**Describe the bug**
Trying to read in a csv file for the compensation matrix using fk.Matrix throws a type error: "TypeError: unsupported operand type(s) for +: 'NoneType' and 'int'". Seems to happen somewhat inconsistently - some csv files work, and some don't work, even if the two csvs contain (what looks to me like) the exact same information.

**Code To Reproduce**
Code to reproduce the behavior:
```
import flowkit as fk
import pandas as pd 
from pandas import DataFrame

comp_file_path = comp_data_path +comp_filename #set the location of the compensation csv file to read in
datafile = data_path +filename #set the location of the sample file to read in
sample = fk.Sample(datafile, cache_original_events=True) #load  file so we can get the detectors for compensation
detectors = [sample.pnn_labels[i] for i in sample.fluoro_indices] #get the detectors 
compmat_df = pd.read_csv(comp_file_path) #load csv as a dataframe 

#attempt to read in csv as a Matrix class
comp_mat = fk.Matrix(
    'my_spill',
    comp_file_path,
    detectors
)
...
```

**Expected behavior**
When it works, I don't get an error and I can successfully apply the compensation to the sample.

**Screenshots**
<img width="914" alt="image" src="https://user-images.githubusercontent.com/64803035/215332305-6bcda0ca-0c77-4a4d-b06c-2ef59776768a.png">

**Desktop (please complete the following information):**
 - OS: Windows 10
 - Python version: Python 3.8.10
 - FlowKit version: FlowKit-0.9.3

**Additional context**
It seems like the header row of the csv file isn't being recognized, so the header variable stays set to "None". However, since the header row seems to match the detectors, I don't know why it isn't being recognized. Below is a link to a folder containing the fcs file and the corresponding spillover matrix in csv format which is currently causing this error.

https://drive.google.com/drive/folders/1UCTwpaPdtx0OFzJzYCvgkZg-60va2-Dc?usp=sharing

**Comment by whitews** [comment]
Hi,

I downloaded the files and was able to parse the comp matrix CSV file without the error. Since you report that the issue is only for some files that are seemingly identical, I suspect the issue may be with the line endings used by the text file where some files may be LF and some CRLF (like the one you shared). These seem to load fine for me on my Linux machine but may cause issues on Windows? That's my best guess, maybe try converting one of the files that triggers the error to have different line ending style and see if that fixes the problem.

-Scott

**Comment by ocohen7** [comment]
Hey Scott - thanks for the tip, turns out some of the files had UTF-8-BOM encoding instead of UTF-8, and it seems to be that was causing the trouble (when I convert to UTF before reading in I don't get the error). 

Thanks again! 
Ora
