### ISSUE TITLE
Missing comma in setup.py

### ISSUE THREAD

**Issue by paulmaschhoff** [whitews/FlowKit#146]
**Describe the bug**
There's a missing comma after `'psutil>=5.8'` in setup.py

**Code To Reproduce**
Under certain circumstances (as far as I can tell, using the most recent versions of pip AND setuptools but either alone is insufficient), pip will catch this omission and throw an error, included at the end.

Really I'm more confused why it doesn't throw an error more of the time. 

**Expected behavior**
A properly-formatted list of requirements gives pip no excuse to throw an error.

**Screenshots**
N/A

**Desktop (please complete the following information):**
 - Passenger Phusion Docker Image
 - Python 3.9
 - FlowKit 0.9.3
 - pip 23.0
 - setuptools 67.2.0

**Additional context**
```
error in FlowKit setup command: 'install_requires' must be a string or list of strings containing valid project/version requirement specifiers; Expected end or semicolon (after version specifier)
#0 19.38           psutil>=5.8scipy
#0 19.38                 ~~~~~^
#0 19.38       [end of output]
```

**Comment by whitews** [comment]
Paul, thanks for finding this. I'm also baffled as to why this obvious syntax error wouldn't throw an error every time setup.py was called. Oh well, we'll get it fixed. Thanks again!
-Scott

**Comment by paulmaschhoff** [comment]
Taking a closer look at pip-compile output of older versions, it seems like `psutil>=5.8scipy` is getting interpreted as a single requirement, and thus the scipy requirement is getting ignored (but you still pull it in via `statsmodels`)

**Comment by whitews** [comment]
Ahh, I see. I've pushed an update with the fix. Note there are a lot of API changes in the current code from the last release. I'm finishing up some of the documentation this week and the 1.0 release should be out soon thereafter.
