### ISSUE TITLE
`Sample` initialization  may  cause samples to have identifier of  `' '` 

### ISSUE THREAD

**Issue by vahvero** [whitews/FlowKit#163]
**Describe the bug**

https://github.com/whitews/FlowKit/blob/e539236c7b480582b80eeacbf47533ff12bb19de/flowkit/_models/sample.py#LL316C1-L327C32 

attempts to infer original filename from 
a fcs file. In my fcs files, the `self.metadata['fil']` is `' '` for all files. I do not know why this is, I suspect it to be related to patient privacy policies.

When attempting to load a `WSP` file which uses these fcs files, no sample is loaded as `' '` constant id filters itself out in https://github.com/whitews/FlowKit/blob/e539236c7b480582b80eeacbf47533ff12bb19de/flowkit/_models/workspace.py#L62. 

**Code To Reproduce**

Code to reproduce the behavior:
```
>>> import flowkit as fk
>>> workspace = fk.Workspace("myfile.wsp", fcs_samples="path/to/myfcs")
>>> print(workspace)
Workspace(0 samples loaded, 4 sample groups)
```

**Expected behavior**

The files are loaded as expected. 

If I change https://github.com/whitews/FlowKit/blob/e539236c7b480582b80eeacbf47533ff12bb19de/flowkit/_models/sample.py#LL316C1-L322C16

to

```
self.original_filename = os.path.basename(fcs_path_or_data)
```

I receive expected behaviour, as `'fil'` metadata is bypassed.

```
>>> print(workspace)
Workspace(65 samples loaded, 4 sample groups)
```

**Desktop (please complete the following information):**
 - OS: [e.g. iOS]: Ubuntu 20.04
 - Python version [e.g. 3.7]: 3.10.8
 - FlowKit version [e.g. 0.4.0]: 1.0.1

**Additional context**

I am not familiar with `fcs` files or what this `fil` key is supposed to return. However, if 
it is supposed to be related to the original filename where `Sample` is originated from, one could
probably change the function to use `os.path.basename` if a path is passed to the `__init__` and use metadata in case the passed argument is not a filepath.

**Comment by whitews** [comment]
Hi,

Yes, the `fil` keyword is supposed to have the original filename and this is typically used by FlowJo to identify the file. However, in some cases like yours the value is not present or the FlowJo workspace was configured to use the actual file names. Internally, it is the `Sample.id` attribute that is used in FlowKit to identify samples. The `original_filename` is used by default to set this ID but can be changed in the Sample class constructor like:

```
sample = Sample(fcs_path, sample_id="set_the_name_here")
````

You can create a list of Sample instances with the correct name this way and pass the list to the Workspace `fcs_samples` and that should work. 

The option to give a directory to the `fcs_samples` argument uses the `load_samples` function as you discovered, which was added for convenience and works for most cases. However, that doesn't have the pass-through argument to set the Sample `id` in the same way.

Hope this helps,
-Scott

**Comment by vahvero** [comment]
Hi,

I will try the suggested solution later.

Would this be something to consider to be changed in the `Workspace` initialization or are you satisfied with the current implementation?
