### ISSUE TITLE
highlight_indices variable not implemented in plot_scatter()? 

### ISSUE THREAD

**Issue by AliceAlmazan** [whitews/FlowKit#176]
**Describe the bug**
I was trying to highlight some samples with `highlight_indices` argument of `plot_scatter()` set up as True. However, I got the following error message: 
got an unexpected keyword argument 'highlight_indices'

**Code To Reproduce**
Code to reproduce the behavior:
```
# SSEA1 is channel index 4 (channel number 5)
SSEA1_xform_events = sample.get_channel_events(4, source='xform')
is_high_SSEA1 = SSEA1_xform_events > 0.82

p = sample.plot_scatter('FL9-H', 'FL12-H', source='xform', highlight_indices=is_high_SSEA1)
show(p)

```

**Expected behavior**
Expected highlighted SSEA1 events with values >0.82

**Screenshots**
<img width="1070" alt="Screenshot 2023-10-09 at 4 19 24 PM" src="https://github.com/whitews/FlowKit/assets/109821186/a05a7612-6a05-4367-84be-31f92efd503b">

**Desktop (please complete the following information):**
 - OS: [macOS 13.6]
 - Python version [3.9]

 - FlowKit version [0.9.3]

**Additional context**
TypeError: plot_scatter() got an unexpected keyword argument 'highlight_indices'

**Comment by whitews** [comment]
Hi Alice,

Looks like you are using FlowKit version 0.9.3 but that feature was added in version 1.0.0. The current version is 1.0.1. Can you try upgrading and retry?

Thanks,
Scott

**Comment by AliceAlmazan** [comment]
Hi Scott, 

My bad. I didn't pay attention to the newer version of the library. All fixed now. Thank you so much!
