### ISSUE TITLE
Pandas 2.0+

### ISSUE THREAD

**Issue by fu** [whitews/FlowKit#177]
**Is your feature request related to a problem? Please describe.**
As a user I would like to use Flowkit with packages that dependent on pandas 2.0+
 
**Describe the solution you'd like**
Everything in Flowkit works except the Seaborn part - maybe plotting should be optional :)

**Describe alternatives you've considered**
None there, really :(

**Comment by arogozhnikov** [comment]
I actually use pandas 2.0 + flowkit (to programmatically import fcs and gate) and it was all fine.

Quick glance through usages of pandas - I don't see anything that would obviously be broken by 2.0

Checked seaborn - they support pandas 2.0 now.

Are there any other reasons to demand pandas <2?

**Comment by whitews** [comment]
Hi Christian & Alex,

The reason it wasn't supported was simply that Pandas v2 only had a release candidate back in Feb 2023 (when the last major FlowKit version was released). The next release will support an updated version of Pandas.

Kind regards,
-Scott

**Comment by whitews** [comment]
completed in 71c6945
