### ISSUE TITLE
0.9.3 setup.py file missing comma in req

### ISSUE THREAD

**Issue by AliceAlmazan** [whitews/FlowKit#183]
**Describe the bug**
https://github.com/whitews/FlowKit/blob/983e60169cd35fcc80b1fc8b111395e374bd6c06/setup.py#L27
missing a comma here in line 27 after 'psutil>=5.8' before scipy. It threw an error when installing the package. 

**Desktop (please complete the following information):**
 - OS: iOS 14.2.1 
 - Python version 3.9
 - FlowKit version 0.9.3

**Comment by whitews** [comment]
Thanks for reporting. This was fixed in an updated version, but I have now yanked this old version from PyPI so it won't happen for other users.

**Comment by AliceAlmazan** [comment]
Thank you so much!
