### ISSUE TITLE
Question to wsp transforms

### ISSUE THREAD

**Issue by Tianmaru** [whitews/FlowKit#184]
I am sorry, but what exactly is this code snippet in `generate_biex_lut` in [_wsp_transforms.py](https://github.com/whitews/FlowKit/blob/master/flowkit/_models/transforms/_wsp_transforms.py) supposed to do?

```
max_channel_value = channel_range + 1
n_points = max_channel_value

step = (max_channel_value - 1) / (n_points - 1)
```

I'm confused, won't `step` always evaluate to 1.0 this way?

**Comment by whitews** [comment]
Your evaluation seems correct. This code was ported from the C implementation of cytolib which claims to have been ported from the original TreeStar Java code. It's the best guide we have for the closed source implementation. Please look through the original and let me know if there is something wrong with the port.

**Comment by Tianmaru** [comment]
Uff, I am sorry, I am not really an expert regarding cpp tbh :sweat_smile:

At first glance, the port seems correct, since cytolib's implementation also includes:

```
EVENT_DATA_TYPE maxChannlVal = channelRange + 1;
int nPoints = maxChannlVal;//4097;//fix the number of points so that it won't lost the precision when scale is set to 256 (i.e. channelRange = 256)

vector<EVENT_DATA_TYPE> positive(nPoints), negative(nPoints), vals(nPoints);
EVENT_DATA_TYPE step = (maxChannlVal-1)/(EVENT_DATA_TYPE)(nPoints -1);
```

However, it's still not clear why step was defined that way and the comment hints that this might be some workaround for `nPoints`.

**Comment by whitews** [comment]
Yeah, it looks like a remnant of a developer experimenting with options. In any case, I ported it "as-is" with the thought that the original context is more important than compact code. If a discrepancy with FlowJo is found at some point, that context could be helpful. Thanks for submitting the issue, we can close this unless there is something else to discuss.

**Comment by Tianmaru** [comment]
Ok, thanks for your attention. I'd love to know what the point of this snippet is, if you figure it out at some point please let me know :+1:
