### ISSUE TITLE
float to string convertion error in time_step

### ISSUE THREAD

**Issue by blabarthe1** [whitews/FlowKit#185]
**Describe the bug**
Really small bug but preventing loading sample : 
flowkit/_models/sample.py", line 287, in __init__
    time_step = float(self.metadata['timestep'])
ValueError: could not convert string to float: '0,001'

**Code To Reproduce**
Code to reproduce the behavior:
```
import flowkit as fk
...
```

**Expected behavior**
just need to change coma to point in fcs

**Screenshots**

**Desktop (please complete the following information):**
 - Python version [e.g. 3.7]
 - FlowKit version [e.g. 0.4.0]

**Additional context**
Add any other context about the problem here. Include traceback here

**Comment by whitews** [comment]
Hi,

Reading through the FCS specification again, it makes clear that decimal values for keywords shall use the "." character. That would make this file non-compliant. I'm very reluctant to add support for non-compliant files, as over time they may combine to create unpredictable behavior.

In this case, you may have a fairly easy workaround. Your trace suggests that FlowIO (the low-level FCS reader/writer I maintain) does read the file without error. So you could use FlowIO to first read the file directly using its FlowData class. With the FlowData instance you could modify the `timestep` keyword value. The FlowKit Sample class constructor will also take a FlowData instance as an argument, so you could then use the modified FlowData instance to create a Sample instance.

Hope this helps,
Scott
