### ISSUE TITLE
Importing Flowkit causes Bus Error

### ISSUE THREAD

**Issue by AkshatJain9** [whitews/FlowKit#187]
**Describe the bug**
I'm having trouble importing flowkit into a python script. For some reason, it causes a bus error upon importing (there is nothing else in the file)

**Code To Reproduce**
Code to reproduce the behavior:
```
import flowkit as fk
```

![Screenshot from 2024-03-13 10-52-48](https://github.com/whitews/FlowKit/assets/59996182/32766c8e-696a-4554-b618-ae81b7cdd991)

**Screenshots**

**Desktop (please complete the following information):**
 - OS: Linux (Ubuntu)
 - Python version - 3.8
 - FlowKit version - 1.0.1

**Additional context**
On every other machine, the script I am running works fine, so I am assuming it could be to do something regarding a flowkit / ubuntu incompatibility.

**Comment by whitews** [comment]
Am I reading correctly that you reduced the script to just the import? What version of Ubuntu are you running and what CPU architecture?

**Comment by AkshatJain9** [comment]
Yes, I am using 20.04.6 and I'm on an x64 architecture

**Comment by whitews** [comment]
That's odd, and any other normal Python script (say with a numpy import) works fine on this machine?

**Comment by AkshatJain9** [comment]
Yep

**Comment by whitews** [comment]
Can you try importing flowutils (a dependency of FlowKit) and see if that also triggers the error?

**Comment by AkshatJain9** [comment]
Sure, that works fine, no error there

**Comment by AkshatJain9** [comment]
Hi, just an update, upgrading to python 3.10 fixed the issue. Feel free to close this, but it could be worth noting this somewhere for anyone in the future.

**Comment by whitews** [comment]
Thanks for the update, not sure what the issue was. Maybe something was borked with the other environment as I have used 3.8 on Ubuntu without issues.
