### ISSUE TITLE
Add `source` kwarg to `Workspace.get_gate_events`

### ISSUE THREAD

**Issue by whitews** [whitews/FlowKit#196]
Add `source` kwarg to `Workspace.get_gate_events` to retrieve gated events in various stages of preprocessing (original, compensated, transformed). This option would be consistent with `Sample` methods. Also, this is made possible by the requirement in FlowJo for a compensation and single set of transforms for each channel (unlike in GatingML / Session where that is not guaranteed).

**Comment by whitews** [comment]
Hi again @hclnyrk,

This will be available in the next release and in the develop branch soon. In the meantime, there is a roundabout way to do this that is described in my comment to this issue:

https://github.com/whitews/FlowKit/issues/195#issuecomment-2086720040

The gist of it is to use the Workspace method `get_gate_membership` to get a Boolean array to filter the Sample events.

Regards,
Scott

**Comment by hclnyrk** [comment]
Thanks for pointing me in the right direction. This is what I ended up doing:

```
#define the gate
gate_of_interest = 'CD8'

#define the transform
asinh_xform = fk.transforms.AsinhTransform(
        'asinh',
        param_t=4194304,
        param_m=3.5,
        param_a=0.0
        )

gated_events_transformed = []

for sample_id in sample_list:

        #this created a bool of the events within the gate
        cd8_event_members = workspace.get_gate_membership(sample_id, gate_name=gate_of_interest)

        #extract the sample
        sample = workspace.get_sample(sample_id)

        #apply the transfrom of interest
        sample.apply_transform(asinh_xform)

        #get a numpy array of the events within the sample (all)
        events = sample.get_events()

        #apply the bool cd8_event_members to gate events (in all channels)
        events_gated = events[cd8_event_members]

        #create a df to hold the gates events (same shape as the get_gate_events df):
        temp = workspace.get_gate_events(sample_id, gate_name=gate_of_interest)
        temp.iloc[:, 1:] = events_gated

        gated_events_transformed.append(temp)

gated_events_transformed_df = pd.concat(gated_events_transformed)
```
