### ISSUE TITLE
Typo in the attribute name for "Matrix" object

### ISSUE THREAD

**Issue by okolupaev** [whitews/FlowKit#206]
**Describe the bug**
In the current version of the FlowKit tutorial- part 2, cell [42]
fluorochromes = comp_mat.fluorochomes
Changing the spelling to more intuitive comp_mat.fluorochromes generates an error (see screenshot) 

**Code To Reproduce**
Code to reproduce the behavior:
```
comp_mat_modified = fk.Matrix(
'custom_splill',
comp_df.values, # use the values from the df we just modified
comp_mat.detectors, # use the same detectors
fluorochromes = comp_mat.fluorochromes #code runs fine if changed to comp_mat.fluorochomes
)
```

**Expected behavior**
Generates an error message

**Screenshots**
<img width="946" alt="Screen Shot 2024-06-26 at 14 25 24" src="https://github.com/whitews/FlowKit/assets/11383390/d4d52aec-65b3-4a7e-a291-a44f1901b15a">

**Desktop (please complete the following information):**
 - OS: [MAacOS 11.7]
 - Python version [3.8.8]
 - FlowKit version [1.1.1]

**Additional context**
Add any other context about the problem here. Include traceback here

**Comment by whitews** [comment]
Thanks for finding and reporting this! Will have a fix shortly.

Kind regards,
Scott

**Comment by whitews** [comment]
@okolupaev 

Version 1.1.2 has been released (available on PyPI) with a fix for this. Please let us know if you find any other issues.

Thanks again!
-Scott
