### ISSUE TITLE
Clustering Comparison: Leiden vs Louvain

### ISSUE THREAD

**Issue by Jonas3wu** [whitews/FlowKit#207]
Hi, Whitews,
Great thanks to your wonderful work for flow cytometry analysis! I did Clustering Comparison: Leiden vs Louvain, BUT after the following codes run in Jupyter notebook, why it generated same outcome picture exactly like yours, even though i had 15 different markers, where to modify? thank you so much.

BEST
Jim

tab20 = plt.colormaps['tab20']
n, p = leiden_clusters.shape

fig, axes = plt.subplots(1, n, figsize=(20, 10))

for i, ax in enumerate(axes.ravel()):
    ax.barh(range(p), leiden_clusters.iloc[i,:], color=tab20(int(i*(20+1)/n)))
    ax.set_xticks([])
    ax.set_yticks([])
    ax.set_frame_on(False)
    ax.set_title(f'C{i:02d}', fontsize=14)
    ax.axvline(0, c=tab20(int(i*(20+1)/n)), ymin=0.05, ymax=0.95)
    
    if i == 0:
        ax.set_yticks(range(p))
        ax.set_yticklabels(leiden_clusters.columns,fontsize=14)
![image](https://github.com/whitews/FlowKit/assets/118767172/c2b622ba-7aac-45a8-b2c2-0e96a674f1cc)

**Comment by whitews** [comment]
Hi Jim,

Difficult to say for sure without seeing your full code, but my guess would be either a browser caching issue or you are inadvertently loading the same 8 color data set that the example notebook is using. Is it correct to say that you are trying to run the same basic pipeline on your own data? If so, I would double check the samples loading in the Workspace instance to make sure they are in fact different.

Hope this helps,
Scott

**Comment by Jonas3wu** [comment]
Dear Scott,

May the 4TH be with you!

I am new to using coding, thank you for your very nice reply, and sorry for my delayed reply. In the initial analysis, dfs[0].head() and X.head() both manifested that it's my data. i restarted a new setup, and paid attention to virtual environment, also renamed my fcs.file folder (previous one was same as yours). now, the issue is gone. cheers!

May i ask how can i reduce the group of cells, a lot of which are similar, and could be merged? Thank you!

Best
Jim

**Comment by Jonas3wu** [comment]
Hi, Scott,

I notice that, as for the antibody0-stained channels, your plot also show -A, no -H. But, each of mine showed both of them, How can i get ride of all the -H?
Thank you so much!

Best
Jim 
![image](https://github.com/whitews/FlowKit/assets/118767172/61891fe9-1744-4ea4-8c25-e88eafd3b64f)

**Comment by whitews** [comment]
Hi Jim,

The data set in the example didn't have height channels for the fluorescent markers. To remove them you would simply filter them out of the pandas DataFrame created in [this section](https://flowkit.readthedocs.io/en/latest/notebooks/advanced/clustering_comparison_leiden_vs_louvain.html#Run-analyze_samples-&-retrieve-gated-events-as-DataFrames) (after the `X` variable is created).

Best,
Scott

**Comment by Jonas3wu** [comment]
Hi, Scott,
Will try. my data plots generated from running on your pipelines is very beautiful. You guys did really great work. Thank you!!

Best
Jim

**Comment by whitews** [comment]
Hi Jim,

Thanks for the kind words! Love hearing that others find the toolkit useful.

-Scott

**Comment by whitews** [comment]
Hi Jim,

Closing this for now, feel free to re-open or post another issue if you are having problems.

-Scott
