### ISSUE TITLE
Referencing transform class via ID in a Dimensions class throws key error when calling .gate_sample()

### ISSUE THREAD

**Issue by Deerer99** [whitews/FlowKit#215]
Description:

Referencing the created transformation class via its transformation ID throws a key error when trying to apply a gate in combination with the mentioned transform. Specifically, when the .gate_sample() method is called.
It could very well be that I overlooked an important detail, but I found no help in the docs and help() function.

Code to reproduce the behavior:
```
import flowkit as fk
path =r"C:\Users\....\file.fcs"
fcs_data = fk.Sample(path,cache_original_events=True,ignore_offset_error=True)

logicle_xform = fk.transforms.LogicleTransform(
    transform_id='logicle',
    param_t=262144,
    param_w=0.5,
    param_m=4.5,
    param_a=0
)

fcs_data.apply_transform(logicle_xform)

#FWS and SWS Total are the channel names for Forward Scatter and Sidewards Scatter in this file fill in your own 

dim_a = fk.Dimension('SWS Total',transformation_ref="logicle", range_max=132000)
dim_b = fk.Dimension('FWS Total',transformation_ref="logicle", range_min=48560)
g_strat = fk.GatingStrategy()
cells_gate = fk.gates.RectangleGate('cells', dimensions=[dim_a, dim_b])
g_strat.add_gate(cells_gate, gate_path=('root',))

res = g_strat.gate_sample(main_fcs_file)
res.report
...
```

I expected the gating strategy to be applied on the transformed events. This means that the values used for specifying the gate would be in transformed values as well. 

 - OS: Windows 11 
 - Python version 3.11.9
 - FlowKit version 1.1.2

Still learning, so it can very well be that I just overlooked something. I suspect the referencing to the transform class from the Dimension class might be different than I expect. But still the only info I found in the documentation was mentioning referencing over ID with str type.

**Comment by whitews** [comment]
Hi @Deerer99,

You're almost there. When using the `GatingStrategy` class, you don't need to manually apply the transform yourself (same with the `Session` class). The idea is that the `GatingStrategy` handles these operations, you just need to give it the instructions and data. I suspect the `KeyError` you are getting is because the dimensions reference a transform that wasn't added to the strategy.

Something like this should work:

```
import flowkit as fk

path =r"C:\Users\....\file.fcs"
fcs_data = fk.Sample(path,cache_original_events=True,ignore_offset_error=True)

# Define transforms
logicle_xform = fk.transforms.LogicleTransform(
    transform_id='logicle',
    param_t=262144,
    param_w=0.5,
    param_m=4.5,
    param_a=0
)

# FWS and SWS Total are the channel names for Forward Scatter and Sidewards Scatter in this file fill in your own 
dim_a = fk.Dimension('SWS Total',transformation_ref="logicle", range_max=132000)
dim_b = fk.Dimension('FWS Total',transformation_ref="logicle", range_min=48560)

# Define gates
cells_gate = fk.gates.RectangleGate('cells', dimensions=[dim_a, dim_b])

g_strat = fk.GatingStrategy()
g_strat.add_transform(logicle_xform)  # <-- Add the transform to the gating strategy
g_strat.add_gate(cells_gate, gate_path=('root',))

res = g_strat.gate_sample(main_fcs_file)
res.report
```

Hope that clears it up, let me know how you get along.

Regards,
Scott

**Comment by Deerer99** [comment]
Wow, thanks so much :D. I didn't realize I had to add it to the gating strategy as well but makes total sense, so one can use different transforms for different gates. Thanks a thousand.
