### ISSUE TITLE
Automatic gating using clustering techniques

### ISSUE THREAD

**Issue by benweinberg89** [whitews/FlowKit#216]
Is there a built-in way to automatically generate gates (e.g. ellipsoid or polygon) using gaussian mixtures models or kmeans clustering etc?
Example:
https://cytoflow.readthedocs.io/en/latest/user_manual/reference/operations/gaussian_2d.html
https://cytoflow.readthedocs.io/en/latest/user_manual/reference/operations/kmeans.html

**Comment by whitews** [comment]
Hi Ben,

Currently there is no built-in mechanism to generate gate boundaries. However, any technique that can produce coordinates for polygon vertices or ellipsoid properties could be used to create a PolygonGate or EllipsoidGate.

Regards,
Scott
