### ISSUE TITLE
Remove a Custom Gate from GatingStrategy

### ISSUE THREAD

**Issue by catcd** [whitews/FlowKit#221]
**Is your feature request related to a problem? Please describe.**  
Currently, it's not possible to remove only a custom gate; removing a gate means deleting the entire gate.

**Describe the solution you'd like**  
Enable the `remove_gate` method to accept a `sample_id` parameter, allowing the removal of a specific custom gate associated with a sample.

**Comment by whitews** [comment]
Hi Cat,

Good catch, that would match the `add_gate` API. I'll include this in the upcoming 1.2.0 release which will be out sometime this week.

Thanks for the suggestion,
Scott

**Comment by catcd** [comment]
**Thank you for your great project.**

**Comment by whitews** [comment]
Hey again,

This functionality has been added to the `develop` branch and will be included in the upcoming 1.2.0 release. Closing this for now, but please reopen or submit another issue if you find something wrong.

A humble request to star this repository if you haven't already, it really helps us out.

Thanks again for submitting the issue and for using FlowKit!
-Scott
