### ISSUE TITLE
FACSDiscover S8 Cellview uses 32 bit encoding -> problem with transforms that assume 18 bit encoding by default

### ISSUE THREAD

**Issue by samdepaauw** [whitews/FlowKit#232]
**Is your feature request related to a problem? Please describe.**
The logicle transformation parameters are hardcoded for 18 bit fcs data. Data collected from new generation flow cytometers such as the BD cellview encodes data in 32 bit. The hardcoded parameters are incompatible with my data. When transforming my data, the transformation yields the same value for all my datapoints. How can the parameters be adjusted in such a way that they allow for 32 bit encoded index data?

**Describe the solution you'd like**
Parameter estimation so that 32 bit index data can be transformed. 

**Describe alternatives you've considered**
Using the max value of float32 as a max value and increasing the channel range by two fold. This did not yield to a successful transformation. 

**Additional context**
I can provide an example plate sort index data.csv file.

**Comment by whitews** [comment]
Hi Sam,

Thanks for submitting this issue. I can look into it and would be interested in getting your input file. It would be helpful to have the output file from the transformation results you are getting as well (in case I cannot replicate the same values). I think you should be able to attach files to this issue. If not, we can figure out a different way to provide them.

Thanks again,
Scott

**Comment by samdepaauw** [comment]
Hi Scott,

Thanks for your response. I attached both an input and output file and code I used to produce the results. The biexponential transformation, for which I used the standard Flowjo parameters, resulted in an array with values of 4096 for untransformed values larger than 18 bit. The untransformed values smaller than 18 bit were transformed. Most of my dataset is larger than 18 bit so filtering these values out would not be productive. 

Thanks in advance and let me know if you need any more from my side. 

Sam

[filtered_facs_index_df.csv](https://github.com/user-attachments/files/17827744/filtered_facs_index_df.csv)
[WSPlogicle_transform_output.csv](https://github.com/user-attachments/files/17827746/WSPlogicle_transform_output.csv)

```
filtered_facs_index_nparr = filtered_facs_index_df.to_numpy()

biex_xform = fk.transforms.WSPBiexTransform(max_value=262144.000029,
                                            positive=4.418540,
                                            width=-10,
                                            negative=0)

WSPlogicle_transform_output = biex_xform.apply(filtered_facs_index_nparr)
```

**Comment by whitews** [comment]
Hi Sam,

I think I see what is going on. You are getting those 4096 values for input values greater than 18-bit values because of the `max_value` value you are using. 262144 is the max 18-bit value and any input values above that will always yield 4096. Changing this to match the max value of your 32-bit input will give you outputs that scale to the larger input range. Consider the following example:

```
import numpy as np
import flowkit as fk

filtered_facs_index_nparr = np.genfromtxt(
    "filtered_facs_index_df.csv",
    delimiter=",",
    skip_header=True
)  # filtered_facs_index_df.to_numpy()

max_value_18bit = 2 ** 18
max_value_32bit = 2 ** 32

biex_xform_18bit = fk.transforms.WSPBiexTransform(
    max_value=max_value_18bit,
    positive=4.418540,
    width=-10,
    negative=0
)

biex_xform_32bit = fk.transforms.WSPBiexTransform(
    max_value=max_value_32bit,
    positive=4.418540,
    width=-10,
    negative=0
)

biex_xform_18bit_output = biex_xform_18bit.apply(filtered_facs_index_nparr)
biex_xform_32bit_output = biex_xform_32bit.apply(filtered_facs_index_nparr)
```

If you examine the difference in those outputs, you will find the 32-bit version never exceeds the max value (the actual max value in your data set is 91,766,344, which never reaches the actual 32-bit max value of 4,294,967,296).

Hope this helps clear things up. Let me know if I've misunderstood your issue or if you have any additional questions.

Kind regards,
Scott

**Comment by samdepaauw** [comment]
Hi Scott,

Thanks for your response! This method works. I tried using the max 32-bit float value myself which did not work, but this makes much more sense. 

Thanks again!

Sam
