### ISSUE TITLE
Windows 10 install error using pip

### ISSUE THREAD

**Issue by NobregaIPI** [whitews/FlowKit#25]
Even after installing the full MS visual studio suite, i get the following error when i try to install fcs.  I'm not sure how to proceed

  ERROR: Command errored out with exit status 1:
   command: 'c:\programdata\anaconda3\python.exe' -u -c 'import sys, setuptools, tokenize; sys.argv[0] = '"'"'C:\\Users\\pauln\\AppData\\Local\\Temp\\pip-install-kg5n55n5\\flowutils\\setup.py'"'"'; __file__='"'"'C:\\Users\\pauln\\AppData\\Local\\Temp\\pip-install-kg5n
55n5\\flowutils\\setup.py'"'"';f=getattr(tokenize, '"'"'open'"'"', open)(__file__);code=f.read().replace('"'"'\r\n'"'"', '"'"'\n'"'"');f.close();exec(compile(code, __file__, '"'"'exec'"'"'))' bdist_wheel -d 'C:\Users\pauln\AppData\Local\Temp\pip-wheel-vajeghm9' --pyth
on-tag cp37
       cwd: C:\Users\pauln\AppData\Local\Temp\pip-install-kg5n55n5\flowutils\
  Complete output (29 lines):
  running bdist_wheel
  running build
  running build_py
  creating build
  creating build\lib.win-amd64-3.7
  creating build\lib.win-amd64-3.7\flowutils
  copying flowutils\compensate.py -> build\lib.win-amd64-3.7\flowutils
  copying flowutils\transforms.py -> build\lib.win-amd64-3.7\flowutils
  copying flowutils\__init__.py -> build\lib.win-amd64-3.7\flowutils
  running build_ext
  building 'flowutils.logicle_c' extension
  creating build\temp.win-amd64-3.7
  creating build\temp.win-amd64-3.7\Release
  creating build\temp.win-amd64-3.7\Release\flowutils
  creating build\temp.win-amd64-3.7\Release\flowutils\logicle_c_ext
  C:\Program Files (x86)\Microsoft Visual Studio\2019\Community\VC\Tools\MSVC\14.22.27905\bin\HostX86\x64\cl.exe /c /nologo /Ox /W3 /GL /DNDEBUG /MT -Ic:\programdata\anaconda3\lib\site-packages\numpy\core\include -Iflowutils/logicle_c_ext -Ic:\programdata\anaconda3\in
clude -Ic:\programdata\anaconda3\include "-IC:\Program Files (x86)\Microsoft Visual Studio\2019\Community\VC\Tools\MSVC\14.22.27905\ATLMFC\include" "-IC:\Program Files (x86)\Microsoft Visual Studio\2019\Community\VC\Tools\MSVC\14.22.27905\include" "-IC:\Program Files
(x86)\Windows Kits\NETFXSDK\4.6.1\include\um" "-IC:\Program Files (x86)\Windows Kits\10\include\10.0.18362.0\ucrt" "-IC:\Program Files (x86)\Windows Kits\10\include\10.0.18362.0\shared" "-IC:\Program Files (x86)\Windows Kits\10\include\10.0.18362.0\um" "-IC:\Program F
iles (x86)\Windows Kits\10\include\10.0.18362.0\winrt" "-IC:\Program Files (x86)\Windows Kits\10\include\10.0.18362.0\cppwinrt" /Tcflowutils/logicle_c_ext/_logicle.c /Fobuild\temp.win-amd64-3.7\Release\flowutils/logicle_c_ext/_logicle.obj -std=c99
  cl : Command line warning D9002 : ignoring unknown option '-std=c99'
  _logicle.c
  c:\programdata\anaconda3\lib\site-packages\numpy\core\include\numpy\npy_1_7_deprecated_api.h(14) : Warning Msg: Using deprecated NumPy API, disable it with #define NPY_NO_DEPRECATED_API NPY_1_7_API_VERSION
  C:\Program Files (x86)\Microsoft Visual Studio\2019\Community\VC\Tools\MSVC\14.22.27905\bin\HostX86\x64\cl.exe /c /nologo /Ox /W3 /GL /DNDEBUG /MT -Ic:\programdata\anaconda3\lib\site-packages\numpy\core\include -Iflowutils/logicle_c_ext -Ic:\programdata\anaconda3\in
clude -Ic:\programdata\anaconda3\include "-IC:\Program Files (x86)\Microsoft Visual Studio\2019\Community\VC\Tools\MSVC\14.22.27905\ATLMFC\include" "-IC:\Program Files (x86)\Microsoft Visual Studio\2019\Community\VC\Tools\MSVC\14.22.27905\include" "-IC:\Program Files
(x86)\Windows Kits\NETFXSDK\4.6.1\include\um" "-IC:\Program Files (x86)\Windows Kits\10\include\10.0.18362.0\ucrt" "-IC:\Program Files (x86)\Windows Kits\10\include\10.0.18362.0\shared" "-IC:\Program Files (x86)\Windows Kits\10\include\10.0.18362.0\um" "-IC:\Program F
iles (x86)\Windows Kits\10\include\10.0.18362.0\winrt" "-IC:\Program Files (x86)\Windows Kits\10\include\10.0.18362.0\cppwinrt" /Tcflowutils/logicle_c_ext/logicle.c /Fobuild\temp.win-amd64-3.7\Release\flowutils/logicle_c_ext/logicle.obj -std=c99
  cl : Command line warning D9002 : ignoring unknown option '-std=c99'
  logicle.c
  flowutils/logicle_c_ext/logicle.c(213): error C2057: expected constant expression
  flowutils/logicle_c_ext/logicle.c(213): error C2466: cannot allocate an array of constant size 0
  flowutils/logicle_c_ext/logicle.c(213): error C2133: 'tmp_taylor': unknown size
  flowutils/logicle_c_ext/logicle.c(321): error C2057: expected constant expression
  flowutils/logicle_c_ext/logicle.c(321): error C2466: cannot allocate an array of constant size 0
  flowutils/logicle_c_ext/logicle.c(321): error C2133: 'tmp_taylor': unknown size
  error: command 'C:\\Program Files (x86)\\Microsoft Visual Studio\\2019\\Community\\VC\\Tools\\MSVC\\14.22.27905\\bin\\HostX86\\x64\\cl.exe' failed with exit status 2
  ----------------------------------------
  ERROR: Failed building wheel for flowutils
  Running setup.py clean for flowutils
Failed to build flowutils
Installing collected packages: flowutils
  Running setup.py install for flowutils ... error
    ERROR: Command errored out with exit status 1:
     command: 'c:\programdata\anaconda3\python.exe' -u -c 'import sys, setuptools, tokenize; sys.argv[0] = '"'"'C:\\Users\\pauln\\AppData\\Local\\Temp\\pip-install-kg5n55n5\\flowutils\\setup.py'"'"'; __file__='"'"'C:\\Users\\pauln\\AppData\\Local\\Temp\\pip-install-kg
5n55n5\\flowutils\\setup.py'"'"';f=getattr(tokenize, '"'"'open'"'"', open)(__file__);code=f.read().replace('"'"'\r\n'"'"', '"'"'\n'"'"');f.close();exec(compile(code, __file__, '"'"'exec'"'"'))' install --record 'C:\Users\pauln\AppData\Local\Temp\pip-record-jgnsrohf\in
stall-record.txt' --single-version-externally-managed --compile
         cwd: C:\Users\pauln\AppData\Local\Temp\pip-install-kg5n55n5\flowutils\
    Complete output (29 lines):
    running install
    running build
    running build_py
    creating build
    creating build\lib.win-amd64-3.7
    creating build\lib.win-amd64-3.7\flowutils
    copying flowutils\compensate.py -> build\lib.win-amd64-3.7\flowutils
    copying flowutils\transforms.py -> build\lib.win-amd64-3.7\flowutils
    copying flowutils\__init__.py -> build\lib.win-amd64-3.7\flowutils
    running build_ext
    building 'flowutils.logicle_c' extension
    creating build\temp.win-amd64-3.7
    creating build\temp.win-amd64-3.7\Release
    creating build\temp.win-amd64-3.7\Release\flowutils
    creating build\temp.win-amd64-3.7\Release\flowutils\logicle_c_ext
    C:\Program Files (x86)\Microsoft Visual Studio\2019\Community\VC\Tools\MSVC\14.22.27905\bin\HostX86\x64\cl.exe /c /nologo /Ox /W3 /GL /DNDEBUG /MT -Ic:\programdata\anaconda3\lib\site-packages\numpy\core\include -Iflowutils/logicle_c_ext -Ic:\programdata\anaconda3\
include -Ic:\programdata\anaconda3\include "-IC:\Program Files (x86)\Microsoft Visual Studio\2019\Community\VC\Tools\MSVC\14.22.27905\ATLMFC\include" "-IC:\Program Files (x86)\Microsoft Visual Studio\2019\Community\VC\Tools\MSVC\14.22.27905\include" "-IC:\Program File
s (x86)\Windows Kits\NETFXSDK\4.6.1\include\um" "-IC:\Program Files (x86)\Windows Kits\10\include\10.0.18362.0\ucrt" "-IC:\Program Files (x86)\Windows Kits\10\include\10.0.18362.0\shared" "-IC:\Program Files (x86)\Windows Kits\10\include\10.0.18362.0\um" "-IC:\Program
 Files (x86)\Windows Kits\10\include\10.0.18362.0\winrt" "-IC:\Program Files (x86)\Windows Kits\10\include\10.0.18362.0\cppwinrt" /Tcflowutils/logicle_c_ext/_logicle.c /Fobuild\temp.win-amd64-3.7\Release\flowutils/logicle_c_ext/_logicle.obj -std=c99
    cl : Command line warning D9002 : ignoring unknown option '-std=c99'
    _logicle.c
    c:\programdata\anaconda3\lib\site-packages\numpy\core\include\numpy\npy_1_7_deprecated_api.h(14) : Warning Msg: Using deprecated NumPy API, disable it with #define NPY_NO_DEPRECATED_API NPY_1_7_API_VERSION
    C:\Program Files (x86)\Microsoft Visual Studio\2019\Community\VC\Tools\MSVC\14.22.27905\bin\HostX86\x64\cl.exe /c /nologo /Ox /W3 /GL /DNDEBUG /MT -Ic:\programdata\anaconda3\lib\site-packages\numpy\core\include -Iflowutils/logicle_c_ext -Ic:\programdata\anaconda3\
include -Ic:\programdata\anaconda3\include "-IC:\Program Files (x86)\Microsoft Visual Studio\2019\Community\VC\Tools\MSVC\14.22.27905\ATLMFC\include" "-IC:\Program Files (x86)\Microsoft Visual Studio\2019\Community\VC\Tools\MSVC\14.22.27905\include" "-IC:\Program File
s (x86)\Windows Kits\NETFXSDK\4.6.1\include\um" "-IC:\Program Files (x86)\Windows Kits\10\include\10.0.18362.0\ucrt" "-IC:\Program Files (x86)\Windows Kits\10\include\10.0.18362.0\shared" "-IC:\Program Files (x86)\Windows Kits\10\include\10.0.18362.0\um" "-IC:\Program
 Files (x86)\Windows Kits\10\include\10.0.18362.0\winrt" "-IC:\Program Files (x86)\Windows Kits\10\include\10.0.18362.0\cppwinrt" /Tcflowutils/logicle_c_ext/logicle.c /Fobuild\temp.win-amd64-3.7\Release\flowutils/logicle_c_ext/logicle.obj -std=c99
    cl : Command line warning D9002 : ignoring unknown option '-std=c99'
    logicle.c
    flowutils/logicle_c_ext/logicle.c(213): error C2057: expected constant expression
    flowutils/logicle_c_ext/logicle.c(213): error C2466: cannot allocate an array of constant size 0
    flowutils/logicle_c_ext/logicle.c(213): error C2133: 'tmp_taylor': unknown size
    flowutils/logicle_c_ext/logicle.c(321): error C2057: expected constant expression
    flowutils/logicle_c_ext/logicle.c(321): error C2466: cannot allocate an array of constant size 0
    flowutils/logicle_c_ext/logicle.c(321): error C2133: 'tmp_taylor': unknown size
    error: command 'C:\\Program Files (x86)\\Microsoft Visual Studio\\2019\\Community\\VC\\Tools\\MSVC\\14.22.27905\\bin\\HostX86\\x64\\cl.exe' failed with exit status 2
    ----------------------------------------
ERROR: Command errored out with exit status 1: 'c:\programdata\anaconda3\python.exe' -u -c 'import sys, setuptools, tokenize; sys.argv[0] = '"'"'C:\\Users\\pauln\\AppData\\Local\\Temp\\pip-install-kg5n55n5\\flowutils\\setup.py'"'"'; __file__='"'"'C:\\Users\\pauln\\App
Data\\Local\\Temp\\pip-install-kg5n55n5\\flowutils\\setup.py'"'"';f=getattr(tokenize, '"'"'open'"'"', open)(__file__);code=f.read().replace('"'"'\r\n'"'"', '"'"'\n'"'"');f.close();exec(compile(code, __file__, '"'"'exec'"'"'))' install --record 'C:\Users\pauln\AppData\
Local\Temp\pip-record-jgnsrohf\install-record.txt' --single-version-externally-managed --compile Check the logs for full command output.

**Comment by whitews** [comment]
@NobregaIPI Paul, thanks for the bug report. I'm not a regular Windows user, so this is good to know. I'll setup a Windows VM and try to track down the issue.

**Comment by whitews** [comment]
@NobregaIPI I was able to reproduce the error on Windows. MS VS doesn't support allocating arrays with a const variable. The bug was in my FlowUtils library and has been fixed, though I haven't yet updated PyPI. Can you clone FlowUtils from the repo and try installing again? Once the fix is verified, I'll update PyPI with FlowUtils version 0.7.1.

**Comment by NobregaIPI** [comment]
@whitews I cloned the project ran: python ./setup.py install

I receive the same error as before.

**Comment by whitews** [comment]
Did you clone the FlowUtils repo? The bug was in that library.

**Comment by NobregaIPI** [comment]
Sorry, mis-read that.  Your fix appears to work fine.

Thanks!

**Comment by whitews** [comment]
Great, thanks for submitting the issue and testing. Let me know if there are any features you'd like to see in FlowKit.
