### ISSUE TITLE
Apply compensation to FCS samples in a Session

### ISSUE THREAD

**Issue by whitews** [whitews/FlowKit#27]
With the new functionality to automatically create a compensation matrix from bead files, there is still no mechanism to apply a compensation matrix to the samples loaded in a Session instance. This relates to #11, as both issues deal with programmatically analyzing FCS files. The GatingStrategy class handles compensation, transformation, and gating. So, the capability to programmatically add gates or apply a compensation matrix should probably be added to the GatingStrategy class with convenient API calls in the Session class.

**Comment by whitews** [comment]
The recent sample group implementation in the Session class makes it unclear how to actually implement this. This functionality relates to custom, "non-gating" analysis of FCS files, thus is more related to the sklearn pipeline support. Moving to the 0.5.0 release.

**Comment by whitews** [comment]
Session sample groups make this relatively easy to do. Closing.

**Comment by mstone-modulus** [comment]
Hi,

Sorry to bump a closed issue, but it's not clear to me how one is supposed to compensate individual samples within the context of a Session. I'd like to compensate each sample with the spillover matrix embedded in their respective .fcs files, but as far as I can tell the `Session` API only supports compensating with a group-wide matrix through `session.add_comp_matrix()`.

Is there a recommend practice for implementing this within the `Session` workflow described in the docs? e.g.

```py
session = fk.Session()
session.add_samples(samples)
# session.add_compensation()    # Compensate by individual matrices
session.add_transform(xform)
session.add_gate(gate)
session.analyze_samples('default')
```

Issue #19 also raised this question but I don't think it was ever addressed directly.

Thanks!

**Comment by whitews** [comment]
@mstone-modulus 

The difficulty here is the mechanism by which GatingML (and FlowJo to some extent) handles compensation. In short, a compensation is associated with a Dimension instance, which in turn is associated with a Gate. Said another way, dimensions are chosen for a gate and processing instructions (both compensation and transformation) are specified for each of those dimensions.

This mechanism was used, I think, to allow maximum flexibility in processing each channel (dimension). This makes more sense if you think in terms of a scatter vs a fluorescence channel...those 2 dimensions would have different compensation & transformation requirements. But in the real world we don't think about a compensation being associated with a channel, rather with an FCS sample as you described.

So, how to apply compensation depends on what you would like to do. There are 2 uses cases for applying compensation: 

1. For gating purposes
2. For simply extracting compensated event data

If you want to use the spill within an FCS file for a gating dimension, you can use the compensation reference string "FCS" when defining a Dimension instance (see the Dimension constructor). There are 2 special reserved strings "uncompensated" and "FCS" that can be used for a compensation reference, the first specifying the dimension's events not be compensated at all and the second instructing that the FCS file's own spillover matrix be used.

For the 2nd case where you simply want to extract compensated event data from a Sample without any gating, I would recommend not using the Session class and use the Sample class directly. To use the internal spill matrix, you can grab it from the Sample metadata dictionary (it's usually the 'spill' or 'spillover' keyword), then get the compensated events. It would look something like this:

```
sample = fk.Sample(fcs_path)

sample.apply_compensation(sample.metadata['spill'])

comp_events = sample.get_events(source='comp')
```

You could also create a transform instance and apply it in a similar way. There's more info in the Sample class docs here:
https://flowkit.readthedocs.io/en/latest/sample.html

Hope this helps you out!
-Scott
