### ISSUE TITLE
Counting points in polygon isn't working properly

### ISSUE THREAD

**Issue by mahakomar11** [whitews/FlowKit#49]
I run General Overview tutorial with the data from examples (the same data as in the tutorial). And almost everything works except 'gate_sample' method. Why 'wind_counts' is so big? Isn't it has to be the same length as 'points' (number of events is 13367 here)?
![Снимок экрана (140)](https://user-images.githubusercontent.com/44169444/85147150-199f7180-b257-11ea-9d8e-043a9cd57c0a.png)

**Comment by whitews** [comment]
HI Maria,

Thanks for reporting this bug. You are right, the array should be way smaller for that example. From you screenshot, it appears you are using Windows and Python 3.8 via Anaconda. What version of Windows are you using? Also, what C compiler and version?

**Comment by whitews** [comment]
Maria,

I am unable to replicate the issue in Windows 10, using either Python 3 installed from python.org or from Anaconda. It appears from your screenshot that you are using Anaconda, yet the paths in the trace indicate Python 3.8, which seems odd as I can only find Python 3.7 in the latest Anaconda installer. If you can provide more about your environment and how you installed FlowKit, I can investigate further.

Thanks,
Scott

**Comment by mahakomar11** [comment]
Hi Scott,

I am using Windows 10. If I remember right I've created my environment by 'conda create -n cyto python=3.8' (version 3.8.3) and installed FlowKit by cloning it from GitHub and running 'python setup.py' in the FlowKit directory. About C compiler, how can I know what compiler and version I use?

**Comment by whitews** [comment]
Hi Maria,

I think most Windows users then to use the C compiler bundled with Microsoft Visual Studio, [available here](https://visualstudio.microsoft.com/downloads/). Can you try installing it and then re-installing FlowKit? It would also be useful to see if setting up a Python 3.7 environment works and also if pip installing FlowKit makes a difference.

Thanks,
Scott

**Comment by whitews** [comment]
Hi Maria,

I'm closing this issue after 10 days of inactivity. If the issue has not been resolved, please feel free to respond and I will re-open and investigate further.
