### ISSUE TITLE
Citation

### ISSUE THREAD

**Issue by afrendeiro** [whitews/FlowKit#50]
**Is your feature request related to a problem? Please describe.**
I would like to cite `flowkit` in a publication in order to fully credit the author.

**Describe the solution you'd like**
A citation with a digital object identifier (DOI).

**Additional context**
If no publication is/will be available shortly, uploading a new release to [Zenodo](https://zenodo.org/) could be a good alternative.

**Comment by whitews** [comment]
Hi Andre,

Thanks for using FlowKit in your project. We are hopeful to have a manuscript for FlowKit by the end of July, once all the major features are implemented. What is the timeline for your publication?

Regards,
Scott

**Comment by afrendeiro** [comment]
Thank you for developing it!

End of July should be fine. I think it will still take a few weeks until it actually gets submitted and then there is still time to add a proper citation during revision, so take your time.

**Comment by afrendeiro** [comment]
For now I used the following as citation:
```bibtex
@Misc{flowkit2020,
author = {Scott White},
title = {{FlowKit}: Intuitive Python framework for flow cytometry analysis and visualization, including GatingML support},
howpublished = {\url{http://github.com/whitews/FlowKit}},
year = {2020}
}
```
Looking forward to the FlowKit manuscript!

**Comment by afrendeiro** [comment]
Hi Scott,

Congratulations on the publication.
Of course, feel free to use anything you like. The preprint/paper I used FlowKit is here: https://scholar.google.com/scholar?cites=2878567822028320997

Best wishes,
Andre

**Comment by whitews** [comment]
Andre, the paper will on the README in the next release.
