### ISSUE TITLE
How to apply transform to FSC / SSC?

### ISSUE THREAD

**Issue by gatoniel** [whitews/FlowKit#54]
**Is your feature request related to a problem? Please describe.**
Hi, I would like to apply the logicle transform to the FSC and SSC channel of the data. It seems that this does not work, since the [`_transform` function](https://github.com/whitews/FlowKit/blob/cd4d40f4b69d18ccd2931a68d3e019476f2c686c/flowkit/_models/sample.py#L549) uses only the channels indicated by `self.fluoro_indices`.

**Describe the solution you'd like**
Remove the `self.fluoro_indices` in the above mentioned function.

**Describe alternatives you've considered**
Until now, I exported the channels into numpy arrays and applied the transform there. But then I cannot use other features of flowkit.

**Additional context**
none

**Comment by whitews** [comment]
Hi Niclas,

Thanks for using FlowKit and taking the time to submit this issue. 

You are correct, the Sample method only applies the transform to the fluorescent channels specified by `fluoro_indices`. As you discovered, the Transform sub-classes can transform any 2-D NumPy array, though this means managing the arrays yourself.

Bi-exponential type transforms are typically applied to only the fluorescent channels, which was the basis of the current behavior. I'd like to keep that behavior as the default, and propose an optional boolean argument `include_scatter` to control whether the specified transform is applied to both fluorescent and scatter channels. The default would be `include_scatter=False`. Would this work for your use case?

**Comment by whitews** [comment]
Niklas, I've added the option to include scatter channels when applying a transform. You can try it out now by cloning and checking out the develop branch. I try to make sure the develop branch passes all the tests, so it is relatively stable. The feature will be incorporated in the upcoming 0.6 release later this month.
