### ISSUE TITLE
When importing flowkit 0.5.0 XMLSchemaParseError is raised.

### ISSUE THREAD

**Issue by ernstdarsac** [whitews/FlowKit#56]
**The bug**
When importing flowkit using ipython (or python in general) XMLSchemaParseError is raised.

**Code To Reproduce**
Code to reproduce the behavior and output obtained:
```
import flowkit 
---------------------------------------------------------------------------
XMLSchemaParseError                       Traceback (most recent call last)
<ipython-input-1-b59a41887bf8> in <module>
----> 1 import flowkit

c:\program files\python37\lib\site-packages\flowkit\__init__.py in <module>
      4 from ._models import gates
      5 from ._models.gating_strategy import GatingStrategy
----> 6 from ._models.session import Session
      7 from ._models.dimension import Dimension, RatioDimension, QuadrantDivider
      8 from ._models.vertex import Vertex

c:\program files\python37\lib\site-packages\flowkit\_models\session.py in <module>
     19 from .._models.transforms._matrix import Matrix
     20 from .._models import gates
---> 21 from .._utils import plot_utils, xml_utils
     22 import warnings
     23

c:\program files\python37\lib\site-packages\flowkit\_utils\xml_utils.py in <module>
      7 import anytree
      8 import re
----> 9 from .._resources import gml_schema
     10 from .._models.dimension import Dimension, RatioDimension, QuadrantDivider
     11 from .._models.vertex import Vertex

c:\program files\python37\lib\site-packages\flowkit\_resources\__init__.py in <module>
     18
     19 gml_schema = etree.XMLSchema(
---> 20     gml_tree
     21 )

src\lxml\xmlschema.pxi in lxml.etree.XMLSchema.__init__()

XMLSchemaParseError: Element '{http://www.w3.org/2001/XMLSchema}group', attribute 'ref': The QName value '{http://www.isac-net.org/std/Gating-ML/v2.0/transformations}Transformation_Group' does not resolve to a(n) model group definition., line 51
```

**Desktop config**
 - OS: Windows 10 1809
 - Python version 3.7.3
 - FlowKit version 0.5.0
 - FlowIO version 0.9.8
 - FlowUtils version 0.8.0
 - lxml version 4.6.1

**Comment by whitews** [comment]
@ernstdarsac Hmm, I cannot seem to reproduce the error in my Windows 10 VM. I'm using the same versions that you list except my Python version is 3.7.4 (which shouldn't make a difference). 

Can you provide more details on your Python setup, like whether you installed Python from python.org or via Anaconda, and how you installed FlowKit (git clone vs pip install vs something else)? Or if there's anything else you can think of that is odd or unusual with your Windows setup, that may give me a clue as to what is going on here.

**Comment by ernstdarsac** [comment]
@whitews I installed Flowkit using pip. I have python installed on a profesionnal computer, hence I have no administrator rights. I assume it may cause some issues? Python was installed through the company app store, which mean probably from python.org.  Here below is the output when I installed flowkit in the terminal (some requirements where already satisfied because I initially tried to uninstall/reinstall a couple of time, hoping that way, to solve the issue)

`H:\>pip install flowkit
Processing c:\users\m254643\appdata\local\pip\cache\wheels\d7\ae\92\a8fb20fb22ce26132980c328282311e1b8cf407375b650d057\flowkit-0.5.0-cp37-cp37m-win_amd64.whl
Requirement already satisfied: seaborn in c:\program files\python37\lib\site-packages (from flowkit) (0.10.0)
Requirement already satisfied: pandas in c:\program files\python37\lib\site-packages (from flowkit) (1.1.3)
Requirement already satisfied: scipy in c:\program files\python37\lib\site-packages (from flowkit) (1.4.1)
Requirement already satisfied: numpy in c:\program files\python37\lib\site-packages (from flowkit) (1.19.2)
Requirement already satisfied: statsmodels in c:\program files\python37\lib\site-packages (from flowkit) (0.12.0)
Requirement already satisfied: bokeh in c:\program files\python37\lib\site-packages (from flowkit) (2.2.3)
Requirement already satisfied: matplotlib in c:\users\m254643\appdata\roaming\python\python37\site-packages (from flowkit) (3.3.2)
Requirement already satisfied: flowio in c:\program files\python37\lib\site-packages (from flowkit) (0.9.8)
Requirement already satisfied: multicoretsne in c:\program files\python37\lib\site-packages (from flowkit) (0.1)
Requirement already satisfied: lxml in c:\program files\python37\lib\site-packages (from flowkit) (4.6.1)
Requirement already satisfied: flowutils in c:\program files\python37\lib\site-packages (from flowkit) (0.8.0)
Requirement already satisfied: anytree in c:\program files\python37\lib\site-packages (from flowkit) (2.8.0)
Requirement already satisfied: sklearn in c:\program files\python37\lib\site-packages (from flowkit) (0.0)
Requirement already satisfied: pytz>=2017.2 in c:\program files\python37\lib\site-packages (from pandas->flowkit) (2019.3)
Requirement already satisfied: python-dateutil>=2.7.3 in c:\program files\python37\lib\site-packages (from pandas->flowkit) (2.8.1)
Requirement already satisfied: patsy>=0.5 in c:\program files\python37\lib\site-packages (from statsmodels->flowkit) (0.5.1)
Requirement already satisfied: typing-extensions>=3.7.4 in c:\program files\python37\lib\site-packages (from bokeh->flowkit) (3.7.4.3)
Requirement already satisfied: tornado>=5.1 in c:\program files\python37\lib\site-packages (from bokeh->flowkit) (6.0.4)
Requirement already satisfied: PyYAML>=3.10 in c:\program files\python37\lib\site-packages (from bokeh->flowkit) (5.3.1)
Requirement already satisfied: Jinja2>=2.7 in c:\program files\python37\lib\site-packages (from bokeh->flowkit) (2.11.2)
Requirement already satisfied: pillow>=7.1.0 in c:\program files\python37\lib\site-packages (from bokeh->flowkit) (7.1.1)
Requirement already satisfied: packaging>=16.8 in c:\program files\python37\lib\site-packages (from bokeh->flowkit) (20.4)
Requirement already satisfied: certifi>=2020.06.20 in c:\program files\python37\lib\site-packages (from matplotlib->flowkit) (2020.6.20)
Requirement already satisfied: kiwisolver>=1.0.1 in c:\program files\python37\lib\site-packages (from matplotlib->flowkit) (1.2.0)
Requirement already satisfied: pyparsing!=2.0.4,!=2.1.2,!=2.1.6,>=2.0.3 in c:\program files\python37\lib\site-packages (from matplotlib->flowkit) (2.4.7)
Requirement already satisfied: cycler>=0.10 in c:\program files\python37\lib\site-packages (from matplotlib->flowkit) (0.10.0)
Requirement already satisfied: cffi in c:\program files\python37\lib\site-packages (from multicoretsne->flowkit) (1.14.1)
Requirement already satisfied: six>=1.9.0 in c:\users\m254643\appdata\roaming\python\python37\site-packages (from anytree->flowkit) (1.14.0)
Requirement already satisfied: scikit-learn in c:\program files\python37\lib\site-packages (from sklearn->flowkit) (0.22.2.post1)
Requirement already satisfied: MarkupSafe>=0.23 in c:\program files\python37\lib\site-packages (from Jinja2>=2.7->bokeh->flowkit) (1.1.1)
Requirement already satisfied: pycparser in c:\program files\python37\lib\site-packages (from cffi->multicoretsne->flowkit) (2.20)
Requirement already satisfied: joblib>=0.11 in c:\program files\python37\lib\site-packages (from scikit-learn->sklearn->flowkit) (0.14.1)
Installing collected packages: flowkit
Successfully installed flowkit-0.5.0`

**Comment by ernstdarsac** [comment]
@whitews I installed Flowkit using pip. I have python installed on a profesionnal computer, hence I have no administrator rights. I assume it may cause some issues? Python was installed through the company app store, which mean probably from python.org. Here below is the output when I installed flowkit in the terminal (some requirements where already satisfied because I initially tried to uninstall/reinstall a couple of time, hoping that way, to solve the issue)

`G:\>pip install flowkit Processing c:\users\username\appdata\local\pip\cache\wheels\d7\ae\92\a8fb20fb22ce26132980c328282311e1b8cf407375b650d057\flowkit-0.5.0-cp37-cp37m-win_amd64.whl Requirement already satisfied: seaborn in c:\program files\python37\lib\site-packages (from flowkit) (0.10.0) Requirement already satisfied: pandas in c:\program files\python37\lib\site-packages (from flowkit) (1.1.3) Requirement already satisfied: scipy in c:\program files\python37\lib\site-packages (from flowkit) (1.4.1) Requirement already satisfied: numpy in c:\program files\python37\lib\site-packages (from flowkit) (1.19.2) Requirement already satisfied: statsmodels in c:\program files\python37\lib\site-packages (from flowkit) (0.12.0) Requirement already satisfied: bokeh in c:\program files\python37\lib\site-packages (from flowkit) (2.2.3) Requirement already satisfied: matplotlib in c:\users\m254643\appdata\roaming\python\python37\site-packages (from flowkit) (3.3.2) Requirement already satisfied: flowio in c:\program files\python37\lib\site-packages (from flowkit) (0.9.8) Requirement already satisfied: multicoretsne in c:\program files\python37\lib\site-packages (from flowkit) (0.1) Requirement already satisfied: lxml in c:\program files\python37\lib\site-packages (from flowkit) (4.6.1) Requirement already satisfied: flowutils in c:\program files\python37\lib\site-packages (from flowkit) (0.8.0) Requirement already satisfied: anytree in c:\program files\python37\lib\site-packages (from flowkit) (2.8.0) Requirement already satisfied: sklearn in c:\program files\python37\lib\site-packages (from flowkit) (0.0) Requirement already satisfied: pytz>=2017.2 in c:\program files\python37\lib\site-packages (from pandas->flowkit) (2019.3) Requirement already satisfied: python-dateutil>=2.7.3 in c:\program files\python37\lib\site-packages (from pandas->flowkit) (2.8.1) Requirement already satisfied: patsy>=0.5 in c:\program files\python37\lib\site-packages (from statsmodels->flowkit) (0.5.1) Requirement already satisfied: typing-extensions>=3.7.4 in c:\program files\python37\lib\site-packages (from bokeh->flowkit) (3.7.4.3) Requirement already satisfied: tornado>=5.1 in c:\program files\python37\lib\site-packages (from bokeh->flowkit) (6.0.4) Requirement already satisfied: PyYAML>=3.10 in c:\program files\python37\lib\site-packages (from bokeh->flowkit) (5.3.1) Requirement already satisfied: Jinja2>=2.7 in c:\program files\python37\lib\site-packages (from bokeh->flowkit) (2.11.2) Requirement already satisfied: pillow>=7.1.0 in c:\program files\python37\lib\site-packages (from bokeh->flowkit) (7.1.1) Requirement already satisfied: packaging>=16.8 in c:\program files\python37\lib\site-packages (from bokeh->flowkit) (20.4) Requirement already satisfied: certifi>=2020.06.20 in c:\program files\python37\lib\site-packages (from matplotlib->flowkit) (2020.6.20) Requirement already satisfied: kiwisolver>=1.0.1 in c:\program files\python37\lib\site-packages (from matplotlib->flowkit) (1.2.0) Requirement already satisfied: pyparsing!=2.0.4,!=2.1.2,!=2.1.6,>=2.0.3 in c:\program files\python37\lib\site-packages (from matplotlib->flowkit) (2.4.7) Requirement already satisfied: cycler>=0.10 in c:\program files\python37\lib\site-packages (from matplotlib->flowkit) (0.10.0) Requirement already satisfied: cffi in c:\program files\python37\lib\site-packages (from multicoretsne->flowkit) (1.14.1) Requirement already satisfied: six>=1.9.0 in c:\users\m254643\appdata\roaming\python\python37\site-packages (from anytree->flowkit) (1.14.0) Requirement already satisfied: scikit-learn in c:\program files\python37\lib\site-packages (from sklearn->flowkit) (0.22.2.post1) Requirement already satisfied: MarkupSafe>=0.23 in c:\program files\python37\lib\site-packages (from Jinja2>=2.7->bokeh->flowkit) (1.1.1) Requirement already satisfied: pycparser in c:\program files\python37\lib\site-packages (from cffi->multicoretsne->flowkit) (2.20) Requirement already satisfied: joblib>=0.11 in c:\program files\python37\lib\site-packages (from scikit-learn->sklearn->flowkit) (0.14.1) Installing collected packages: flowkit Successfully installed flowkit-0.5.0`

**Comment by whitews** [comment]
@ernstdarsac I see. Are you familiar with Python virtual environments? If you have `virtualenv` installed as part of your Python setup, try setting up a virtual environment and trying to install within it.

Also, do you have Visual Studio installed? It would have been necessary (or some other C compiler) for building the C extensions in FlowUtils and FlowKit. And related to that, make sure you have numpy installed prior to installing FlowKit or FlowUtils.

**Comment by ernstdarsac** [comment]
@whitews I did not know `virtualenv` but that 'solved' the issue allowing me to import, and play with it within the virtual env. Thank you very much.
