### ISSUE TITLE
Biex transform

### ISSUE THREAD

**Issue by Louis-Pujol** [whitews/FlowKit#58]
Hello,

I want to work with a FlowJo analysis file (.wsp) and get an error when I try to load it with import_flowjo_workspace because of biex transformation in the analysis. Is it planned in the future to make the API compatible with this transformation ?

Yours,
Louis
![error](https://user-images.githubusercontent.com/52413616/108211279-cc98d580-712c-11eb-8fb8-93af559a0f58.png)

**Comment by whitews** [comment]
Hi Louis,

Thanks for using FlowKit and taking the time to submit this issue. 

Yes, in fact, I have regular contact with the FlowJo development team and they have provided the details for the Biex transform. This has already been implemented in the `develop` branch and will be included in the upcoming 0.6 release. Version 0.6 will be released as soon as I finish the FlowJo workspace export feature.

In the meantime, it would be helpful if you could test the import of your FJ workspace file with the develop branch. The develop branch is relatively stable and I try to avoid pushing commits that fail any tests. The main issue is that there may be API changes that I have not yet documented. If you'd like to test it out, here's how to install the develop branch:

    pip install git+https://github.com/whitews/flowkit@develop

Let me know if it works for your file or if you run into additional issues.

Thanks,
Scott

**Comment by Louis-Pujol** [comment]
Thank you very much for your answer. I had followed your instruction and install the develop branch. Running again my code, I get new errors :

![OSerror](https://user-images.githubusercontent.com/52413616/108235174-e1359780-7145-11eb-9346-ed6b50cfbcac.png)

![ValueError](https://user-images.githubusercontent.com/52413616/108235189-e397f180-7145-11eb-87d3-29bdee16eae2.png)

If you have an idea on how to fix it, let me know,
Thanks,
Louis

**Comment by whitews** [comment]
Thanks Louis, I have run into this problem with a few workspace files I have tested. 

The way the biex transform is implemented in FlowJo is by use of a set of lookup tables. These tables map various combinations of the transform parameters (the sliders in the FJ interface for the transform dialog window) to input and output event data. In this case, the width parameter value in your file, -19.952623, is not found in the lookup tables they provided.

Looking through the tables I have, it appears the closest valid value to your file is -15.848932. I have just experimented with changing the width value in FlowJo for a simple workspace and, indeed, the slider value of -20 corresponds to the value you have within the wsp XML.

Looks like I am missing a few of their lookup tables. I will ask the FlowJo devs if they can provide these. Will leave this issue open and update you when I hear something.

Thanks again for reporting this,
Scott

**Comment by Louis-Pujol** [comment]
Hi Scott,

Thanks for your help, it is highly appreciated,
Louis

**Comment by whitews** [comment]
Louis,

I've modified the FlowJo biex implementation to dynamically create the lookup tables. Can you check your code/data against the latest dev branch commit?

Thanks,
Scott

**Comment by Louis-Pujol** [comment]
Hi Scott,

Now I have an issue with the parameter "maxRange", here is a screenshot : 

![Screenshot_20210406_155609](https://user-images.githubusercontent.com/52413616/113722648-e9936300-96f0-11eb-8221-66a3d9a60997.png)

Thanks,
Louis

**Comment by whitews** [comment]
Hi Louis,

I just submitted a fix for these value checks, can you retry your code now?

Thanks!
Scott

**Comment by Louis-Pujol** [comment]
Hi Scott,

It works, thank you
