### ISSUE TITLE
fasinh transform

### ISSUE THREAD

**Issue by andreas-wilm** [whitews/FlowKit#60]
**Is your feature request related to a problem? Please describe.**

I'm trying to load FlowJo workspaces that use the fasinh transformation. Similar to [this issue](https://github.com/whitews/FlowKit/issues/58), I get:

    ValueError: FlowJo transform type fasinh is undocumented and not supported in FlowKit. Please edit the workspace in FlowJo and save all channel transformations as either linear, log, or logicle

In my case FlowJo files are created upstream and I can't edit the workspaces. 

**Describe the solution you'd like**

Ideally FlowKit should have the fasinh transformation implemented. [FlowWorkspace](http://rglab.github.io/flowWorkspace/reference/flowjo_fasinh.html) and [GGcyto](https://www.bioconductor.org/packages/release/bioc/vignettes/ggcyto/inst/doc/Top_features_of_ggcyto.html) have this implemented. I'm not sure though, if there is an official reference from the FlowJo developers

**Comment by whitews** [comment]
Hi Andreas,

I'll experiment with the FlowWorkspace `fasinh` implementation and see how well it matches the FlowJo results. I am currently trying to add missing biex LUTs for #58, which is rather tedious as it involves manually exporting the myriad of parameter combinations. I'll add this issue to the next milestone and report back.

Thanks!

**Comment by andreas-wilm** [comment]
Great. Thanks! For the sake of completeness: this is described in [Gating-ML 2.0](http://flowcyt.sourceforge.net/gating/latest.pdf) paragraph 6.4 / page 69.

**Comment by andreas-wilm** [comment]
BTW I'm happy to help if you give me a few pointers for testing etc.

**Comment by andreas-wilm** [comment]
Wonderful. Thanks so much! This looks good as far as I can see
