### ISSUE TITLE
Docs for GatingStrategy gate_sample() incorrect

### ISSUE THREAD

**Issue by andreas-wilm** [whitews/FlowKit#61]
Hello, 

the [GatingStrategy docs](https://flowkit.readthedocs.io/en/latest/gating_strategy.html) mention that `gate_sample()` should  

> apply a gate to a sample, returning a dictionary where gate ID is the key, and the value contains the event indices for events in the Sample which are contained by the gate

However,  it actually returns a GatingResults instance (whose `get_gate_indices()` achieves the above)

Best, Andreas

**Comment by whitews** [comment]
Thanks Andreas, the docs have been updated.
