### ISSUE TITLE
Memory Error

### ISSUE THREAD

**Issue by Panzax** [whitews/FlowKit#64]
I am doing data analysis for a biosensor thesis project and FlowKit seems to be unable to analyze my data. Below I have attached pictures of my code and of the error given. My flow cytometry data has 14 channels and 20,000 events. This is less data than the examples posted in the FlowKit Github. However, when I try to use the fks.analyze_samples() function I get an error indicating that not enough memory could be allocated to gate the sample. What could be causing this?

Thank you for any help

![Screenshot 2021-04-06 130448](https://user-images.githubusercontent.com/10876087/113771787-b2b15300-96d8-11eb-90c0-09d53a145ed4.png)
![Screenshot 2021-04-06 130416](https://user-images.githubusercontent.com/10876087/113771791-b3e28000-96d8-11eb-95eb-b066cce576ba.png)

**Comment by whitews** [comment]
Hi Martin,

Yeah, something's definitely wrong here. That array in the points_in_polygon shouldn't have a size of half a trillion. Would it be possible to share your data file and notebook to see if I can reproduce on my end?

Thanks,
Scott

**Comment by whitews** [comment]
Also, let me know what OS and Python version you are using.

**Comment by Panzax** [comment]
Hi Scott,
Thank you so much for the quick response! This is for a thesis project due
in two weeks so I am very thankful for the help. I have attached the FSC
file I am working with, along with the pictures in my post and my Jupyder
notebook. I believe I am running python 3.9.2.. Please let me know if
there's any way I can help solve the problem!

Sincerely,
Martin

**Comment by Panzax** [comment]
P.S. I forgot to say my OS, I am running Windows 10 Home O.S. Build
18363.1440n (off an Asus Zenbook UX303B laptop with 12GB of RAM).

**Comment by Panzax** [comment]
P.S.S sorry for the messy notebook, I just realized how bad it is LOL. The
only part of the code that is relevant is the part that I screenshot and
sent to you, the rest is scratch. As you may notice I am converting
FlowCytometryTools polygates into FlowKit gates. Aside from that little
quirk, the code seems to match what is on the GitHub examples almost
exactly.

**Comment by whitews** [comment]
Martin,

Don't think the attachments work in the GitHub replies. Can you send them directly to my email:

whitews@gmail.com

thx!

**Comment by Panzax** [comment]
Hi Scott,

I just sent the email!

-Martin

**Comment by whitews** [comment]
Got'em, will let you know what I find out.

**Comment by Panzax** [comment]
Thank you! I'll keep my eyes peeled for an update. Let me know if there's
anything else I can do to help!

- Martin

**Comment by whitews** [comment]
Hey Martin,

I can run your code fine on my Linux machine. I suspect the issue might be with the C compiler in Windows. What C compiler and version are you running?

**Comment by Panzax** [comment]
Oh how interesting. I am not sure what C compiler I am using. Do you know
how I could find out? Perhaps this could be the source of the issue if I
don't have one at all

- Martin

**Comment by whitews** [comment]
How did you install FlowKit (via pip, git clone/setup.py, etc)? Do you have MS Visual Studio installed? That could include a C compiler.

**Comment by Panzax** [comment]
I installed FlowKit via pip, I have MS Visual Studio installed as well
https://wiki.python.org/moin/WindowsCompilers
following that tutorial I also installed Microsoft Build tools and
updated setuptools.

**Comment by whitews** [comment]
Okay, let me setup a Windows virtual machine and try your setup...will report back. Sorry for all the back and forth, we'll get it sorted out!

**Comment by Panzax** [comment]
Thank you so much! And no problem at all, I really appreciate the help.
Should I attempt to uninstall and reinstall FlowKit? It may have been that
my setuptools was out of date, since when I updated it there was a recent
update that installed.

- Martin

**Comment by whitews** [comment]
Hi Martin,

Your code is also running okay on my Windows VM. You mentioned you are running Python 3.9, how did you install Python? Just want to make sure I'm replicating your setup as close as I can.

Thanks,
Scott

**Comment by Panzax** [comment]
I installed python via the python site (just went on and downloaded it
there). I believe I have the problem but I'm unsure how to solve it:

Multicore TSNE requires CMake, which needs a C-compiler to be installed. Here
is a link to the description of the problem
<https://stackoverflow.com/questions/35869564/cmake-on-windows>.

I think this is the origin of all of my issues. How do I reset my C
compiler? The answer above is a little above my head technically

- Martin

**Comment by whitews** [comment]
Martin,

Multicore TSNE was removed as a dependency in the upcoming version of FlowKit. Can you try installing from the `develop` branch and see if that works? 

`pip install git+https://github.com/whitews/flowkit.git@develop`

**Comment by Panzax** [comment]
Scott,

Oh that may work. For some reason the command wont run on my python, I have
pip installed and it is working properly, here's the error

[image: image.png]
-Martin

**Comment by whitews** [comment]
Martin, that image didn't come through. BTW, you'll need git installed to use that command.

**Comment by Panzax** [comment]
Scott,

I installed git but I am getting this error:


C:\Users\Martin>pip install git+
***@***.***
Collecting ***@***.***
  Cloning https://github.com/whitews/flowkit.git (to revision develop) to
c:\users\martin\appdata\local\temp\pip-req-build-r62rl8x2
  Running command git clone -q https://github.com/whitews/flowkit.git
'C:\Users\Martin\AppData\Local\Temp\pip-req-build-r62rl8x2'
  Running command git checkout -b develop --track origin/develop
  Branch 'develop' set up to track remote branch 'develop' from 'origin'.
  Switched to a new branch 'develop'
    ERROR: Command errored out with exit status 1:
     command:
'C:\Users\Martin\AppData\Local\Microsoft\WindowsApps\PythonSoftwareFoundation.Python.3.9_qbz5n2kfra8p0\python.exe'
-c 'import sys, setuptools, tokenize; sys.argv[0] =
'"'"'C:\\Users\\Martin\\AppData\\Local\\Temp\\pip-req-build-r62rl8x2\\setup.py'"'"';
__file__='"'"'C:\\Users\\Martin\\AppData\\Local\\Temp\\pip-req-build-r62rl8x2\\setup.py'"'"';f=getattr(tokenize,
'"'"'open'"'"', open)(__file__);code=f.read().replace('"'"'\r\n'"'"',
'"'"'\n'"'"');f.close();exec(compile(code, __file__, '"'"'exec'"'"'))'
egg_info --egg-base
'C:\Users\Martin\AppData\Local\Temp\pip-pip-egg-info-pkmbp6xp'
         cwd: C:\Users\Martin\AppData\Local\Temp\pip-req-build-r62rl8x2\
    Complete output (11 lines):
    Traceback (most recent call last):
      File "<string>", line 1, in <module>
      File
"C:\Users\Martin\AppData\Local\Temp\pip-req-build-r62rl8x2\setup.py", line
2, in <module>
        import numpy as np
      File
"C:\Users\Martin\AppData\Local\Packages\PythonSoftwareFoundation.Python.3.9_qbz5n2kfra8p0\LocalCache\local-packages\Python39\site-packages\numpy\__init__.py",
line 143, in <module>
        from . import _distributor_init
      File
"C:\Users\Martin\AppData\Local\Packages\PythonSoftwareFoundation.Python.3.9_qbz5n2kfra8p0\LocalCache\local-packages\Python39\site-packages\numpy\_distributor_init.py",
line 26, in <module>
        WinDLL(os.path.abspath(filename))
      File "C:\Program
Files\WindowsApps\PythonSoftwareFoundation.Python.3.9_3.9.752.0_x64__qbz5n2kfra8p0\lib\ctypes\__init__.py",
line 374, in __init__
        self._handle = _dlopen(self._name, mode)
    OSError: [WinError 193] %1 is not a valid Win32 application
    ----------------------------------------
WARNING: Discarding ***@***.***
Command errored out with exit status 1: python setup.py egg_info Check the
logs for full command output.
ERROR: Command errored out with exit status 1: python setup.py egg_info
Check the logs for full command output.

Not sure why Murphy's law is in full swing for this project, lol

**Comment by whitews** [comment]
Yeah, Murphy does seem to be having his fun with us, huh? Okay, can you try installing Python 3.8 and see if that works?

**Comment by Panzax** [comment]
Yes I will do that -- I have a friend's windows computer and it was able to
run the command, I think something inside my python packages/caches has
gone awry. I'll see if my script runs on this new computer and then if it
can't I'll try uninstalling and reinstalling everything and going from there

Will report back shortly.

Thank you again for your help, it is immensely appreciated

-Martin

**Comment by Panzax** [comment]
Update:

I was able to get it to run (kind of). If I completely uninstalled
everything, then reinstalled everything minus the flowkit/flowutils/flowio
package, then use the git command you sent previously, then the code runs
out of a python 3.9.2 terminal. However, it still won't run through
anaconda (despite going through the whole process I detailed above, but in
anaconda). I'm not sure why python 3.8 is so averse to the FlowKit package,
but that seems to be the issue. I have some questions about the package
while I have your attention:

1) If I wanted to gather mean fluorescence (channel FL1-A) of my data after
applying two (simple) polygon gates to it, what methods would I use?
Specifically, I am unsure how the fks.analyze_data method works. Does it
actually remove the gated events *in fks itself*? And if so, how do I
access only those gated events fluorescence data? The most obvious answer
to me would be to go through each sample and use the following code

for sample in fks.get_group_samples(sample_grp):
    sample.get_channel_data(2) #FL1-A is indexed at channel 2

however, that gives me this error:

  File
"C:\Users\Martin\AppData\Local\Packages\PythonSoftwareFoundation.Python.3.9_qbz5n2kfra8p0\LocalCache\local-packages\Python39\site-packages\flowkit\_models\sample.py",
line 602, in get_channel_data
    channel_data = self._transformed_events[idx, channel_index]
TypeError: 'NoneType' object is not subscriptable

Could I be looking for one of these instead?

   - get_orig_events(subsample=False)
   - get_raw_events(subsample=False)
   - get_comp_events(subsample=False)
   - get_ transformed _events(subsample=False)

2) Additionally, I get the same error as above (pasted below this question
as well) when I attempt to save my sample FCS data to a new FCS file using
this code:

sample = fks.get_group_samples(sample_grp)[0]
sample.export('test.fcs',directory=saving_dir) #saving_dir is the filepath
to the save folder directory

  File
"C:\Users\Martin\AppData\Local\Packages\PythonSoftwareFoundation.Python.3.9_qbz5n2kfra8p0\LocalCache\local-packages\Python39\site-packages\flowkit\_models\sample.py",
line 967, in export
    events = self._transformed_events[idx, :]
TypeError: 'NoneType' object is not subscriptable

3) I really appreciate all of your help, however, for both of our times'
sake, would it be easier perhaps for you to help me get working code to
merely collect the mean fluorescence from a single channel (FL1-A) and call
it there? That is all I really need to do and I am supposed to have my
results for this paper done by Saturday evening. If you have any more time
to spare tomorrow I would be more than grateful if you could help me a
little more.

Thank you
Martin

**Comment by whitews** [comment]
Hi Martin,

Well, at least we got you with a working setup. I generally try to avoid Anaconda because of situations like this where the dependency stack can be tricky. I find it better to use Python virtualenv environments since they allow more straight-forward control of dependencies and versions. 

For your questions:

> I am unsure how the fks.analyze_data method works. Does it
> actually remove the gated events *in fks itself*? 

No, the events are not removed. The way the results are stored is a boolean array of the same size as the number of events in each Sample. Basically it stores which event indices are in the gate.

> how do I access only those gated events fluorescence data?

You would use the Session method `get_gate_indices` to get the indices of the gated events per Sample. Now, one thing to keep in mind is that the Sample instance events have not been processed. This gets complicated to explain, but because each gate dimension has it's own compensation and transform "instructions" a gating strategy can have gates for the same channel with different comps / transforms.

I'll add a convenience method in the Session to make this easier and create an example notebook showing the usage.

> sample.get_channel_data(2) #FL1-A is indexed at channel 2
> 
> gives me this error:
> 
>   File
> "C:\Users\Martin\AppData\Local\Packages\PythonSoftwareFoundation.Python.3.9_qbz5n2kfra8p0\LocalCache\local-packages\Python39\site-packages\flowkit\_models\sample.py",
> line 602, in get_channel_data
>     channel_data = self._transformed_events[idx, channel_index]
> TypeError: 'NoneType' object is not subscriptable

Sample.get_channel_data() has an option for the "source" that controls the type of events that are returned (raw, comp, xform, etc.). The default is 'xform' but you haven't applied a transform to the Sample so there are no transformed events to return. 

> help me get working code to merely collect the mean fluorescence from a single channel (FL1-A)

Sure, let me add that Session method and create the example notebook. Should have it later today.

**Comment by Panzax** [comment]
Thank you so much for your help! This has really been a life saver (I am an
Honors student at Whitman College and I think I bit off a little more than
I could chew taking on this data analysis all on my own). I will certainly
credit you & FlowKit in my final 'published' thesis project!

- Martin

**Comment by whitews** [comment]
Happy to help, and having real-world feedback like this hopefully improved the package for others. Thank you for sticking with it.

Ok, so I've added a few Session methods that should make this easier, particularly `get_gate_events`. There is also a new notebook in the examples directory showing how to use that method and does a Mean Fluorescence Intensity (MFI) comparison between 2 gated populations. You can find it here (should render in the browser):

https://github.com/whitews/FlowKit/blob/develop/examples/flowkit-session-compare-mfi-of-gated-events.ipynb

Let me know if that is in the ballpark of what you are trying to do.

-Scott

**Comment by Panzax** [comment]
Yes that is definitely in the ballpark of what I am trying to do. Should I
reinstall the package to get the new session methods?

- Martin

**Comment by whitews** [comment]
Yes, you'll have to upgrade the package. Something like this should work:

`pip install --upgrade git+https://github.com/whitews/flowkit.git@develop`
