### ISSUE TITLE
offset bug report

### ISSUE THREAD

**Issue by HaidYi** [whitews/FlowKit#66]
**Describe the bug**

I tried to read a .FCS file downloaded from https://flowrepository.org/, but it occurred the following bug. I am sure this file is not corrupted because there is no such bug when I read it using Flowkit (0.5.0) and Flowio (0.9.8).

> ValueError: FCS file 0001.FCS reports a data offset that is off by 1. Set `ignore_offset_error=True` to force reading in this file.

**Code To Reproduce**
Code to reproduce the behavior:
```
import flowkit as fk
sample = fk.Sample("0001.FCS")
...
```

**Expected behavior**
A correct data reading.

**Desktop (please complete the following information):**
 - OS: Ubuntu 18.04
 - Python version: 3.8
 - FlowKit version: 0.6.1
 - FlowIO version: 0.9.11

**Comment by whitews** [comment]
Hi,

Can you retry reading in the file with the ignore offset flag set to True:

`sample = fk.Sample("0001.FCS", ignore_offset_error=True)`

The history of what is happening here is there are many FCS files floating around that have a data offset that is incorrectly reported (off by 1) yet are not corrupt. However, a user recently came upon an FCS file with the off by 1 issue where the file **was** corrupt. 

So the decision was made for FlowKit (and FlowIO) to be more transparent regarding these "off by 1" files so the user can be aware and if they choose, to explicitly force reading in these files. While somewhat inconvenient, it was deemed the better approach to prevent an unsuspecting user from going forward with analysis on potentially corrupt data.

Let me know how the above option works for your case.

Thanks,
Scott

**Comment by HaidYi** [comment]
Hello Scott, thanks for your quick reply. Now, the data reading is working well for me.
