### ISSUE TITLE
Value change when creating Sample from dataframe

### ISSUE THREAD

**Issue by andreas-wilm** [whitews/FlowKit#78]
**Describe the bug**

When creating a sample from a dataframe I see some values change.

**Code To Reproduce**

iPython session:

```
In [1]: import flowkit as fk

In [2]: import numpy as np

In [3]: import pandas as pd

In [4]: df = pd.DataFrame([44434214.0], columns = ['A'], dtype=np.float64)

In [5]: df
Out[5]:
            A
0  44434214.0

In [6]: sample = fk.Sample(df)

In [7]: sample.as_dataframe(source="raw")
Out[7]:
pnn           A
pns
0    44434216.0
...
```

**Expected behavior**

The value return from `sample.as_dataframe()` should be the same as used for creating the sample

**Desktop (please complete the following information):**
 - OS: OS X 11.5.2
 - Python version 3.9.6
 - FlowKit version 0.6.1 and 0.7.0

**Additional context**

This fails with and without defining `dtype` for the dataframe.

This seems to only fail for floats above 8 digits, irrespective if their are to the left or the right of the decimal place. But this should be more places even if the FCS was just single precision IEEE floating point (unless I misunderstand the specification).

**Comment by whitews** [comment]
Hi Andreas,

Thanks for submitting this issue. This is happening in FlowIO, and is related to the single precision floating point. Single precision floats are limited to 7 decimal places. The minimal example of the issue is:

```
import array from array

array('f', [44434214.0])
```

Looks like the FCS 3.1 specification does allow double precision, but that's not currently supported in FlowIO. I will look into adding that. Do you happen to have an FCS file with double precision I could use as an example?

Thanks,
Scott

**Comment by andreas-wilm** [comment]
Thanks Scott!

Sorry for submitting to the wrong repo. 

I was under the possibly wrong impression that the "single precision IEEE floating point" in the standard was actually referring to a IEEE 754 32-bit base-2 floating-point.

I can look for double precision FCS files. Not sure if I have some. In my case I came across this issue, because I was trying to create an FCS file (rather than reading one)

**Comment by whitews** [comment]
No worries, it's fine to have reported here. 

So, I'm not sure I've encountered a double FCS file either. Without an "official" example I'm somewhat hesitant to add support for it in FlowIO. I think what I will do is create an experimental branch in FlowIO so we can do some testing. Would that be amenable to you?

Also, I'm curious as to what you plan to do with the resulting FCS file? I wonder how other apps and libraries would handle it.

**Comment by andreas-wilm** [comment]
I have to admit, that I'm actually abusing the feature: I am trying to store a 16 character cell barcode, split into two channels. This was originally genomics data converted to FCS. I might as well split it into more columns to avoid the issue altogether.

**Comment by whitews** [comment]
Haha, I see! In that case, these are actually integers that you want to store, right? The FCS 3.1 spec doesn't say there is a limit for integer types (though all the examples use 16 bit), and they are specified to only unsigned. Depending on how large your barcode values are, perhaps a 32-bit unsigned integer would fit. FlowIO would still have to be updated to handle this, but would probably be more-straightforward to implement.

**Comment by whitews** [comment]
Oh, 16 characters, then the 32-bit ints will leave you with the same problem. Your approach of splitting is probably best then, unless u could save a separate file (HDF5, CSV, etc.) as a bar code LUT with the event indices and codes.

**Comment by andreas-wilm** [comment]
Yeah in my case I need it in the same file for gating. Anyway, let me close this. If anything this should go to FlowIO and even then it's debatable whether this will ever be needed in non-artificial cases
