### ISSUE TITLE
from .. import _utils_c as utils_c

### ISSUE THREAD

**Issue by Alinkno** [whitews/FlowKit#88]
**Describe the bug**
I have installed the flowKit package and your gate_utils.py code block says: from.. "Import _utils_c as utils_c", "can not import name '_utils_c' from 'flowkit" because there is no _utils_c module in the flowkit directory

**Comment by whitews** [comment]
Hi Alinko,

The _utils_c module is compiled from the C extension. You will need a C compiler to build it. What OS are you using?

**Comment by Alinkno** [comment]
Thank you very much for your reply. I used The Windows system and developed it on PyCharm



------------------&nbsp;原始邮件&nbsp;------------------
发件人:                                                                                                                        "whitews/FlowKit"                                                                                    ***@***.***&gt;;
发送时间:&nbsp;2021年11月17日(星期三) 晚上10:20
***@***.***&gt;;
***@***.******@***.***&gt;;
主题:&nbsp;Re: [whitews/FlowKit] from .. import _utils_c as utils_c (Issue #88)





 
Hi Alinko,
 
The _utils_c module is compiled from the C extension. You will need a C compiler to build it. What OS are you using?
 
—
You are receiving this because you authored the thread.
Reply to this email directly, view it on GitHub, or unsubscribe.
Triage notifications on the go with GitHub Mobile for iOS or Android.

**Comment by whitews** [comment]
Ok, you will need a C compiler & the easiest way is to download Microsoft Visual Studio and make sure the c compiler component is installed (I think it is by default).

**Comment by Alinkno** [comment]
Thank you very much.I'm new to Python and don't fully understand what you mean. from ..&nbsp; "Import _utils_c as utils_c" imports the _utils_c.py file from flowKit. How can I get the _utils_c.py file? Your package I downloaded looks like this.

You mean to compile a file in flowkit/utils_c_ext?





------------------&nbsp;原始邮件&nbsp;------------------
发件人:                                                                                                                        "whitews/FlowKit"                                                                                    ***@***.***&gt;;
发送时间:&nbsp;2021年11月17日(星期三) 晚上10:20
***@***.***&gt;;
***@***.******@***.***&gt;;
主题:&nbsp;Re: [whitews/FlowKit] from .. import _utils_c as utils_c (Issue #88)





 
Hi Alinko,
 
The _utils_c module is compiled from the C extension. You will need a C compiler to build it. What OS are you using?
 
—
You are receiving this because you authored the thread.
Reply to this email directly, view it on GitHub, or unsubscribe.
Triage notifications on the go with GitHub Mobile for iOS or Android.

**Comment by whitews** [comment]
Alinkno,

Are you installing via pip or have you cloned the GitHub repository?

**Comment by Alinkno** [comment]
Thank you very much for your reply! I have downloaded the repository locally and the PyCharm environment has piped your FlowKit library.





My error page is as follows！











------------------&nbsp;原始邮件&nbsp;------------------
发件人:                                                                                                                        "whitews/FlowKit"                                                                                    ***@***.***&gt;;
发送时间:&nbsp;2021年11月18日(星期四) 上午10:55
***@***.***&gt;;
***@***.******@***.***&gt;;
主题:&nbsp;Re: [whitews/FlowKit] from .. import _utils_c as utils_c (Issue #88)





 
Alinkno,
 
Are you installing via pip or have you cloned the GitHub repository?
 
—
You are receiving this because you authored the thread.
Reply to this email directly, view it on GitHub, or unsubscribe.
Triage notifications on the go with GitHub Mobile for iOS or Android.

**Comment by whitews** [comment]
I see, to use the library from a local directory you can build the extension using the following command:

`python setup.py build_ext --inplace`

If you want the local library installed in, say, a virtual environment, you would first activate that environment and then run the regular setup install process:

`python setup.py install`

**Comment by whitews** [comment]
Hi @Alinkno,

Were you able to successfully get FlowKit installed & working?

**Comment by Alinkno** [comment]
Thank you very much for solving the above problems. But there is still a problem with the relative path within the project, which I am working on. In addition, please kindly check that there is a Fitsne module using Python in your example, but I have not succeeded in PIP it.In addition, I used the picture in the email I sent to you, I wonder if you can see it?The following is the installation command, but I have been unable to install it successfully.





------------------&nbsp;原始邮件&nbsp;------------------
发件人:                                                                                                                        "whitews/FlowKit"                                                                                    ***@***.***&gt;;
发送时间:&nbsp;2021年11月20日(星期六) 凌晨1:23
***@***.***&gt;;
***@***.******@***.***&gt;;
主题:&nbsp;Re: [whitews/FlowKit] from .. import _utils_c as utils_c (Issue #88)





 
Hi @Alinkno,
 
Were you able to successfully get FlowKit installed &amp; working?
 
—
You are receiving this because you were mentioned.
Reply to this email directly, view it on GitHub, or unsubscribe.
Triage notifications on the go with GitHub Mobile for iOS or Android.

**Comment by whitews** [comment]
Alinkno,

Sorry, the images do not show up. Can you paste the text?

For fitsne, that is not a dependency of FlowKit, was just used in an example notebook. For help installing it, you would have to submit an issue to the fitsne developers.

**Comment by Alinkno** [comment]
Thank you very much for your help.
