### ISSUE TITLE
Implement plotting of gates with Sample events

### ISSUE THREAD

**Issue by whitews** [whitews/FlowKit#9]
Not sure if this should be done in Sample or GatingStrategy class. Maybe in some new GatingResults class?

**Comment by ncthomas** [comment]
Would be great to have this feature in asap. Fantastic work on the package.

**Comment by whitews** [comment]
Thanks Niclas, it has been on my radar for quite some time to create a higher level flow library. Plotting gates is one of the major goals of this project. 

As I stated above, I'm not 100% sure where this functionality should live. On one hand, the Sample class has no knowledge of gates, and probably shouldn't as more than one gating strategy can be applied to a Sample. On the flip side, the GatingStrategy class shouldn't really have to manage Sample objects. My plan is to have the `gate_sample` method return a new GatingResult object that holds the boolean arrays for gate membership along with some more useful population statistics, and then put the gate plotting methods there.

**Comment by whitews** [comment]
This functionality will so in the Session class. Plotting of gates will require handling the gate type and the parent gate events. Depending on the gate type, different plot types may be required. Options for which events to display need to be considered, i.e. filtering parent events or showing all events.

**Comment by whitews** [comment]
initial plotting of polygon gates working in 754f2f52b76e85838041199e2047aa631d00d98e

**Comment by whitews** [comment]
plotting of rectangle, range, and ellipse gates working in a319c3a90bb24899c667988b610c24ebb76dec07

Plotting of quadrant gates will come in a 0.4.x release. Not sure if boolean gates can be plotted. Closing this issue.
