### ISSUE TITLE
import flowjo workspace with groups containing samples with no gates / subpopulations

### ISSUE THREAD

**Issue by blabarthe1** [whitews/FlowKit#91]
**Describe the bug**
Importing flowjo workspace with groups containing samples with no gates / subpopulations will induce 'KeyError' line 494 of wsp_uilts.py : 
```
flowkit/flowkit/_utils/wsp_utils.py in parse_wsp(workspace_file_or_path, ignore_transforms)
    492 
    493         for group_sample_id in group_dict['samples']:
--> 494             sample_dict = wsp_samples[group_sample_id]
    495             sample_name = sample_dict['sample_name']
    496 
```

This KeyError is du to these lines in wsp_utils.py : 
```
--> 408     if sample_root_sub_pop_el is None:
 409               continue
```
Is there a logic for not storing samples in wsp_samples dictionnary when there is no gates or subpopulations ?

**Code To Reproduce**
Code to reproduce the behavior:
inputs files to reproduce the error can be find here : 
[https://flowrepository.org/experiments/1062/download_ziped_files](url)
```
import flowkit as fk
xml_path = OMIP_Hammer.wsp
fk.parse_wsp(xml_path)
```

**Expected behavior**
wsp parsed with no error or at least an exception explaining why a sample with no gate is not stored

**Screenshots**

**Desktop (please complete the following information):**
 - OS: ubuntu 20.04
 - Python version 3.8.10
 - FlowKit version 0.8.2

**Additional context**
Add any other context about the problem here. Include traceback here

**Comment by blabarthe1** [comment]
Hi scott,

Thanks a lot for your answer and for your work. Flowkit is really useful.
I've done the modification you've suggested by returning the list of all
empty samples and ignoring their import in groups and it works perfectly in
my case.

Thanks again

Regards
Baptiste

Le ven. 4 mars 2022 à 16:57, Scott White ***@***.***> a
écrit :

**Comment by whitews** [comment]
Baptiste,

I've implemented a fix for this in the latest commit on the develop branch. If you can verify this works on your side, we can close this. Thanks!

**Comment by blabarthe1** [comment]
Scott,

I've tested and it works for my use case.
Thanks !!
Baptiste
