### ISSUE TITLE
unable to parse gate in wsp when spillover matrix is embeded into wsp

### ISSUE THREAD

**Issue by blabarthe1** [whitews/FlowKit#92]
**Describe the bug**
When spillover matix is embeded into flowjo workspace, channel names are automatically renamed to Fj_Comp_{channel name} by flowjo. It create error here : 
gating_strategy.py in _preprocess_sample_events(self, sample, gate, cache_events)
    523                 # names that will match
    524                 if not dim_comp:
--> 525                     raise LookupError(
    526                         "%s is not found as a channel label or channel reference in %s" % (dim_id, sample)
    527                     )

**Code To Reproduce**
Code to reproduce the behavior:
data can be downloaded here : 
https://flowrepository.org/id/FR-FCM-ZZ36
.jo file can be transform to wsp using flowjo (I can also provide wsp but don't know how attach data in bug report)
```
import flowkit as fk
wsp_path = '23.10.2012.OMIP.wsp'
fcs_paths = ['pbmc_luca.fcs']
sample_lists = [fk.Sample(str(f), ignore_offset_error=True) for f in fcs_paths]
session = fk.Session(sample_lists)
session.import_flowjo_workspace(
                wsp_path,
                ignore_missing_files=True
            )
session.analyze_samples('All Samples', 'pbmc_luca.fcs',verbose=True)
...
```

**Expected behavior**
Apply the compensation matrix embeded into workspace to raw data when channels are renamed to Fj_comp_{channel name}  and than compute gates

**Screenshots**

**Desktop (please complete the following information):**
 - OS: Linux
 - Python 3.8.8
 - FlowKit 0.8.2

**Additional context**
Add any other context about the problem here. Include traceback here

**Comment by blabarthe1** [comment]
Sorry renaming is not automatic it's user defined. The prefix is defined in the spillover matrix part of wsp.
for example for the specific wsp defined previously : 
<Matrices>
     <transforms:spilloverMatrix spectral="0"  prefix="Comp-"  name="Comp Matrix"  editable="0"  color="#c0c0c0"  version="FlowJo-10.8.1"  status="FINALIZED"  transforms:id="a2129995-fa5f-444a-8664-bc14e434aa9b"  suffix="" >
(line 59 of  23.10.2012.OMIP.wsp)

**Comment by whitews** [comment]
Hi Baptiste,

Can you check something for me in FlowJo? There is an issue/bug in FlowJo when converting v9 jo files to v10 wsp files where custom comp matrices (i.e. not the embedded spill in the FCS metadata) are not re-associated with the samples. I've spoken to the FlowJo devs about this and they confirmed the issue. Can you check in FlowJo whether the referenced comp is a custom one and if it is properly associated with the samples?

Thanks,
Scott

**Comment by blabarthe1** [comment]
Hi Scott,

You are right the wsp fie is kind of corrupted.
I'm sorry to polute your bug dashboard. 
Maybe that there is an other canal I could reach flowkit devs before opening bugs ?
Because I've allready an other question regarding duplicated gates in wsp (same population name but different gate ids)
This bug can be closed.
