### ISSUE TITLE
GatingML compliance & Transformation

### ISSUE THREAD

**Issue by jainaditi0204** [whitews/FlowKit#94]
**Describe the bug**
Hello, 
I am trying to read a GatingML file (exported via FCSexpress), but when I do so, flowkit throws an error message saying that the file is not GatingML compliant. Since, it is a third party software, I also tried creating the gates using Flowkit, and then exporting the GatingML, and then trying to read it in again using fk.parse_gating_xml(gml_path), however, it still throws the same error. 

**Code To Reproduce**
Code to reproduce the behavior:
```
import flowkit as fk
..
..
session.export_gml(output_file_path, group_name)
```

**Expected behavior**
No error messages while reading a GatingML file using fk.parse_gating_xml(file_path)

**Screenshots**

**Desktop (please complete the following information):**
 - OS: Fedora34
 - Python version : 3.9.10
 - FlowKit version : 0.8.2

**Additional context**
For more context, I am trying to read in multiple fcs files, and therefore, have created a session. I have also created gates manually (since I couldn't read in the gatingML exported via FCSexpress, and retrieve the g_strat). Consequently, I used the available function export_gml(...) as described in the documentation, but when I try to read it again via the parse_gating_xml(...) function, it says the file isn't gating compliant.

**Comment by whitews** [comment]
Hi Aditi,

I assume this is the same issue that you emailed me about. Did both the original FCSExpress and the manually made GML file use "#" characters in the gate names? Can you try removing those characters and seeing if the GML files parse without errors?

Thanks,
Scott

**Comment by jainaditi0204** [comment]
Yes, it worked now. Thank you!
