### ISSUE TITLE
Transformation functions

### ISSUE THREAD

**Issue by jainaditi0204** [whitews/FlowKit#95]
**Describe the bug**
Hello, 
I am trying to apply transformation functions to the coordinates of different gates that I've created, but I'm not sure if I can specify that. So far, I know that the transformation functions apply to a Sample, or can be added to an entire session or an entire gating strategy, but I can't customize it. Maybe I'm missing something here, but I cannot figure it out from the documentation.
Additionally, I also used a simple numpy array to check how the transformed values should look like (using Logical transformation), but it doesn't seem to change them at all. 

**Code To Reproduce**
Code to reproduce the behavior:
```
import numpy as np
import flowkit as fk

a = np.array([1, 10, 100, 1000, 10000, 10000])
x_form = fk.transforms.LogicleTransform('logical', param_t=262144.000024287, param_a=0, param_w=0.835145901824217, param_m=4.49906901701087)
x_form_data = x_form.apply(a)
```
OUTPUT: [    1    10   100  1000 10000 10000]

**Expected behavior**
Logically transformed values

**Screenshots**

**Desktop (please complete the following information):**
 - OS : Fedora34
 - Python version : 3.9.10
 - FlowKit version : 0.8.2

**Additional context**
Add any other context about the problem here. Include traceback here

**Comment by jainaditi0204** [comment]
Hi, 

That is strange. 
Yes, I downloaded it via pip.

**Comment by whitews** [comment]
Let's test whether you get different values for a different transform. Try the AsinhTransform and see if that works.

**Comment by jainaditi0204** [comment]
I am still getting the same output. 

x_form = fk.transforms.AsinhTransform('asinh', param_t=262144, param_a=0, param_m=5) 

Output: 
[    1    10   100  1000 10000 10000]
[    1    10   100  1000 10000 10000]

**Comment by whitews** [comment]
Hmm, this is quite odd. And that is after running `x_form.apply()` right?

Also, do you have a C compiler (like gcc) installed? That would be necessary to build the extensions, but seems like it would have thrown an error if it was missing.

Can you create a fresh virtualenv and retest?

**Comment by jainaditi0204** [comment]
The transformation works now :)

Also, could you also address the first issue with transformation and Sample class?

**Comment by whitews** [comment]
> I am trying to apply transformation functions to the coordinates of different gates that I've created, but I'm not sure if I can specify that. So far, I know that the transformation functions apply to a Sample, or can be added to an entire session or an entire gating strategy, but I can't customize it. Maybe I'm missing something here, but I cannot figure it out from the documentation.

A transformation instance can be added to a Session's sample group (or a GatingStrategy). Take note of the transform's ID, you can associate the transform with any Dimension instance you want. All the different gate types will take Dimension instances, and these not only tell which parameter to use for a gate but also how to compensate and/or transform the events in that dimension/channel.

This allows all the flexibility needed for any combination. You can have a PolygonGate with 2 Dimension instances and each one could specify a comp matrix and/or transform just for that channel. For compensation it doesn't make much sense to use different spillover matrices for different channels...but you could!

As an example, let's say you have a transform with the ID "my_logicle", you can associate the transform with a Dimension like so:

```
dim1 = fk.Dimension(
    'CD4 PE-A',
    compensation_ref='uncompensated',
    transformation_ref='my_logicle'
)
```

When `dim1` is used in a gate and applied to an event array, all the necessary compensation & transformation pre-processing will be done for you.

Does that help clarify how it works?

**Comment by jainaditi0204** [comment]
Thank you for the clarification! :)
