### ISSUE TITLE
Install issue [windows 10, python 3.9.9]

### ISSUE THREAD

**Issue by decameter-narced** [whitews/FlowKit#97]
Hi there,

Unfortunately, I receive an error when installing FlowKit via pip:
OS = windows 10
Python = 3.9.9

>pip install flowkit
Collecting flowkit
  Using cached FlowKit-0.8.2.tar.gz (76 kB)
  Preparing metadata (setup.py) ... error
  error: subprocess-exited-with-error

  × python setup.py egg_info did not run successfully.
  │ exit code: 1
  ╰─> [8 lines of output]
      Traceback (most recent call last):
        File "<string>", line 2, in <module>
        File "<pip-setuptools-caller>", line 34, in <module>
        File "[BLANKED]\pip-install-uelo7bcp\flowkit_0442e6e9134843f69e2df9f23c60dae0\setup.py", line 23, in <module>
          long_description = fh.read()
        File "[BLANKED]\Python\Python39\lib\encodings\cp1252.py", line 23, in decode
          return codecs.charmap_decode(input,self.errors,decoding_table)[0]
      UnicodeDecodeError: 'charmap' codec can't decode byte 0x9d in position 7538: character maps to <undefined>
      [end of output]

  note: This error originates from a subprocess, and is likely not a problem with pip.
error: metadata-generation-failed

× Encountered error while generating package metadata.
╰─> See above for output.

note: This is an issue with the package mentioned above, not pip.
hint: See above for details.

I also tried to start by installing the dependencies one by one. FlowIO installation worked as a gem. FlowUtils however also gave an error (cfr. below). I spotted a similar error post [2019] where the issue seemed have been resolved. Also similar to the reported issue, I tried updating Microsoft Visual C++, but that did not help. 

pip install flowutils
Collecting flowutils
  Using cached FlowUtils-0.9.5.tar.gz (11 kB)
  Preparing metadata (setup.py) ... done
Requirement already satisfied: numpy>=1.17 in [BLANKED]\python\python39\lib\site-packages (from flowutils) (1.21.4)
Building wheels for collected packages: flowutils
  Building wheel for flowutils (setup.py) ... error
  error: subprocess-exited-with-error

  × python setup.py bdist_wheel did not run successfully.
  │ exit code: 1
  ╰─> [12 lines of output]
      running bdist_wheel
      running build
      running build_py
      creating build
      creating build\lib.win-amd64-cpython-39
      creating build\lib.win-amd64-cpython-39\flowutils
      copying flowutils\compensate.py -> build\lib.win-amd64-cpython-39\flowutils
      copying flowutils\transforms.py -> build\lib.win-amd64-cpython-39\flowutils
      copying flowutils\__init__.py -> build\lib.win-amd64-cpython-39\flowutils
      running build_ext
      building 'flowutils.logicle_c' extension
      error: Microsoft Visual C++ 14.0 or greater is required. Get it with "Microsoft C++ Build Tools": https://visualstudio.microsoft.com/visual-cpp-build-tools/
      [end of output]

  note: This error originates from a subprocess, and is likely not a problem with pip.
  ERROR: Failed building wheel for flowutils
  Running setup.py clean for flowutils
Failed to build flowutils
Installing collected packages: flowutils
  Running setup.py install for flowutils ... error
  error: subprocess-exited-with-error

  × Running setup.py install for flowutils did not run successfully.
  │ exit code: 1
  ╰─> [14 lines of output]
      running install
      [BLANKED]\Python\Python39\lib\site-packages\setuptools\command\install.py:34: SetuptoolsDeprecationWarning: setup.py install is deprecated. Use build and pip and other standards-based tools.
        warnings.warn(
      running build
      running build_py
      creating build
      creating build\lib.win-amd64-cpython-39
      creating build\lib.win-amd64-cpython-39\flowutils
      copying flowutils\compensate.py -> build\lib.win-amd64-cpython-39\flowutils
      copying flowutils\transforms.py -> build\lib.win-amd64-cpython-39\flowutils
      copying flowutils\__init__.py -> build\lib.win-amd64-cpython-39\flowutils
      running build_ext
      building 'flowutils.logicle_c' extension
      error: Microsoft Visual C++ 14.0 or greater is required. Get it with "Microsoft C++ Build Tools": https://visualstudio.microsoft.com/visual-cpp-build-tools/
      [end of output]

  note: This error originates from a subprocess, and is likely not a problem with pip.
error: legacy-install-failure

× Encountered error while trying to install package.
╰─> flowutils

note: This is an issue with the package mentioned above, not pip.
hint: See above for output from the failure.

Thanks for any help!

Kind regards

**Comment by decameter-narced** [comment]
Hi,

Thanks for the quick reply!
I have version 16.11.11.

Kind regards

**Comment by whitews** [comment]
That's odd. Are you sure have installed the C++ build tools (in the link from the error message)?

**Comment by decameter-narced** [comment]
Yes:
![afbeelding](https://user-images.githubusercontent.com/103516976/163119344-f50968b5-3203-4aa9-862c-252a2a49b00f.png)

**Comment by decameter-narced** [comment]
The issue with flowutils is resolved: I had to uninstall older Microsoft Visual C++ versions that might have been interfering.
The error message I receive with installing flowkit remains though.

Generally, the recommended troubleshooting for the "python setup.py egg_info did not run successfully.
│ exit code: 1" error seems to be to try (i) upgrade pip, (ii), upgrade setuptools, (iii) install ez_setup. None of these resolve the issue unfortunately

pip = 22.0.4
setuptools = 62.1.0
ez-setup = 0.9

**Comment by decameter-narced** [comment]
Hi Scott,

Thanks for looking into the error for flowkit! From the develop branch clone, I got byte position 7959 thrown in the error:

[BLANKED]>git clone https://github.com/whitews/FlowKit.git
Cloning into 'FlowKit'...
remote: Enumerating objects: 5425, done.
remote: Counting objects: 100% (3211/3211), done.
remote: Compressing objects: 100% (1782/1782), done.
remote: Total 5425 (delta 2192), reused 2411 (delta 1403), pack-reused 2214
Receiving objects: 100% (5425/5425), 90.26 MiB | 15.68 MiB/s, done.
Resolving deltas: 100% (3745/3745), done.
Updating files: 100% (231/231), done.

[BLANKED]>cd FlowKit

[BLANKED]>python setup.py install
Traceback (most recent call last):
  File "[BLANKED]\FlowKit\setup.py", line 23, in <module>
    long_description = fh.read()
  File "[BLANKED]\AppData\Local\Programs\Python\Python39\lib\encodings\cp1252.py", line 23, in decode
    return codecs.charmap_decode(input,self.errors,decoding_table)[0]
UnicodeDecodeError: 'charmap' codec can't decode byte 0x9d in position 7959: character maps to <undefined>

**Comment by whitews** [comment]
Ok, pull the latest commit and try again. I think this was related to a copy/paste of the citation that included "special" open & close quote characters from MS Word.

**Comment by decameter-narced** [comment]
Hi Scott,

Yes that works perfectly!! Thanks a lot!

Kind regards,

Maarten

**Comment by whitews** [comment]
If I could ask for one more test before we close this. I've made one more slight change to setup.py related to this. Can you pull and verify it still installs on your Windows system?

**Comment by decameter-narced** [comment]
Sure! Happy to help. Is it in the latest commit?

**Comment by decameter-narced** [comment]
Affirmative; the pull still installs on my system :-)

Best,

Maarten

**Comment by whitews** [comment]
Thanks Maarten!
